force-app/main/default/objects/CARE_App_Enrolled_SA__c/CARE_App_Enrolled_SA__c.object-meta.xml
<CustomObject>
    <description>SA(s) affected by the transaction in the CARE Application object</description>
    <label>CARE App Enrolled SA</label>
    <nameField>
        <displayFormat>CTSA{000000000}</displayFormat>
        <label>NAME  (APP SA Seq)</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE App Enrolled SA</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/APPLICATION__c.field-meta.xml
<CustomField>
    <fullName>APPLICATION__c</fullName>
    <label>APPLICATION</label>
    <referenceTo>CARE_Application__c</referenceTo>
    <relationshipLabel>CARE App Enrolled SA</relationshipLabel>
    <relationshipName>CARE_App_Enrolled_SA</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/CC_CL_CD__c.field-meta.xml
<CustomField>
    <fullName>CC_CL_CD__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CC CL CD</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/CCB_CONTACT_TYPE__c.field-meta.xml
<CustomField>
    <fullName>CCB_CONTACT_TYPE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB CONTACT TYPE</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/PER_ID__c.field-meta.xml
<CustomField>
    <fullName>PER_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PER ID</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/RETRO_END_DATE__c.field-meta.xml
<CustomField>
    <fullName>RETRO_END_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RETRO END DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/RETRO_START_DATE__c.field-meta.xml
<CustomField>
    <fullName>RETRO_START_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RETRO START DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/SA_ID__c.field-meta.xml
<CustomField>
    <fullName>SA_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SA ID</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/Service_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Service_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Agreement</label>
    <referenceTo>EI_Site__c</referenceTo>
    <relationshipLabel>CARE App Enrolled SA</relationshipLabel>
    <relationshipName>CARE_App_Enrolled_SA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/CARE_Application__c.object-meta.xml
<CustomObject>
    <label>CARE Application</label>
    <nameField>
        <displayFormat>CT-{0000000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE Application</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_Application__c/fields/APPLICATION_STATUS__c.field-meta.xml
<CustomField>
    <fullName>APPLICATION_STATUS__c</fullName>
    <inlineHelpText>Status of Enrollment</inlineHelpText>
    <label>APPLICATION STATUS</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Decision Made</fullName>
            </value>
            <value>
                <fullName>Staged for CC&amp;B</fullName>
            </value>
            <value>
                <fullName>Sent to CC&amp;B</fullName>
            </value>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CARE_CI_CC__c.field-meta.xml
<CustomField>
    <fullName>CARE_CI_CC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CARE CI CC</label>
    <referenceTo>CARE_CI_CC__c</referenceTo>
    <relationshipLabel>CARE Application</relationshipLabel>
    <relationshipName>CARE_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CC_CL_CD__c.field-meta.xml
<CustomField>
    <fullName>CC_CL_CD__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DISCOUNT TYPE</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CCB_CONTACT_CODE2__c.field-meta.xml
<CustomField>
    <fullName>CCB_CONTACT_CODE2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB CONTACT CODE2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CCB_CONTACT_CODE__c.field-meta.xml
<CustomField>
    <fullName>CCB_CONTACT_CODE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB CONTACT CODE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CCB_CONTACT_DESC2__c.field-meta.xml
<CustomField>
    <fullName>CCB_CONTACT_DESC2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB CONTACT DESC2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CCB_CONTACT_DESC__c.field-meta.xml
<CustomField>
    <fullName>CCB_CONTACT_DESC__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB CONTACT DESC</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CCB_Contact_Type_No__c.field-meta.xml
<CustomField>
    <fullName>CCB_Contact_Type_No__c</fullName>
    <description>The care type no for the contact code selected</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB Contact Type No</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/COMMENTS__c.field-meta.xml
<CustomField>
    <fullName>COMMENTS__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>COMMENTS</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/PER_ID__c.field-meta.xml
<CustomField>
    <fullName>PER_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PER ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/PROCESSED_DATE__c.field-meta.xml
<CustomField>
    <fullName>PROCESSED_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PROCESSED DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/RECEIVED_DATE__c.field-meta.xml
<CustomField>
    <fullName>RECEIVED_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RECEIVED DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/RETRO_END_DATE__c.field-meta.xml
<CustomField>
    <fullName>RETRO_END_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RETRO END DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/SOURCE_CHANNEL_TYPE__c.field-meta.xml
<CustomField>
    <fullName>SOURCE_CHANNEL_TYPE__c</fullName>
    <label>SOURCE CHANNEL TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Demand Status</fullName>
            </value>
            <value>
                <fullName>CARE Force.com</fullName>
            </value>
            <value>
                <fullName>CARE SMS</fullName>
            </value>
            <value>
                <fullName>CARE Flatsite</fullName>
            </value>
            <value>
                <fullName>CARE MyEnergy</fullName>
            </value>
            <value>
                <fullName>Regular App</fullName>
            </value>
            <value>
                <fullName>SoundBite</fullName>
            </value>
            <value>
                <fullName>Phone Enrollment</fullName>
            </value>
            <value>
                <fullName>Web Download</fullName>
            </value>
            <value>
                <fullName>Kiosk</fullName>
            </value>
            <value>
                <fullName>CASE/Adjustment</fullName>
            </value>
            <value>
                <fullName>CASE/Reinstatement</fullName>
            </value>
            <value>
                <fullName>CASE/Transfer</fullName>
            </value>
            <value>
                <fullName>CASE/Commodity</fullName>
            </value>
            <value>
                <fullName>PEV/Adjustment</fullName>
            </value>
            <value>
                <fullName>Enroll/Adjustment</fullName>
            </value>
            <value>
                <fullName>Bill Insert</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Allconnect</fullName>
            </value>
            <value>
                <fullName>ESA Enrollment</fullName>
            </value>
            <value>
                <fullName>DAC GT Enrollment</fullName>
            </value>
            <value>
                <fullName>Water Agency/IOU</fullName>
            </value>
            <value>
                <fullName>Batch</fullName>
            </value>
            <value>
                <fullName>DataXport Enrollment</fullName>
            </value>
            <value>
                <fullName>DataXport PEV Notice</fullName>
            </value>
            <value>
                <fullName>CARE New_Mover</fullName>
            </value>
            <value>
                <fullName>CARE IVR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/START_DATE__c.field-meta.xml
<CustomField>
    <fullName>START_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>START DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_CI_CC__c/CARE_CI_CC__c.object-meta.xml
<CustomObject>
    <description>CARE CI CC data from CC&amp;B</description>
    <label>CARE CI CC</label>
    <nameField>
        <displayFormat>CICC{0000000000}</displayFormat>
        <label>Sequence No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE CI CC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_CI_CC__c/fields/DESCR254__c.field-meta.xml
<CustomField>
    <fullName>DESCR254__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DESCR254</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CARE_CI_CC__c/fields/PER_ID__c.field-meta.xml
<CustomField>
    <fullName>PER_ID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>PER ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_CI_CC__c/fields/USER_ID__c.field-meta.xml
<CustomField>
    <fullName>USER_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>USER ID</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Type__c/CARE_Type__c.object-meta.xml
<CustomObject>
    <label>Reason/Contact Maintenance</label>
    <nameField>
        <displayFormat>CTNO-{000000}</displayFormat>
        <label>Seq No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reason/Contact Maintenance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_Type__c/fields/COMMENTS__c.field-meta.xml
<CustomField>
    <fullName>COMMENTS__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>COMMENTS</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CARE_Type__c/fields/END_DATE__c.field-meta.xml
<CustomField>
    <fullName>END_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>END DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_Type__c/fields/TYPE_CODE__c.field-meta.xml
<CustomField>
    <fullName>TYPE_CODE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TYPE CODE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Type__c/fields/TYPE_NO__c.field-meta.xml
<CustomField>
    <fullName>TYPE_NO__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>TYPE NO</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EI_Site__c/EI_Site__c.object-meta.xml
<CustomObject>
    <description>Sites are locations associated with Accounts, where work is performed.</description>
    <label>Site/Service Agreement</label>
    <nameField>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site/Service Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/EI_Site__c/fields/Svc_Type_Code_EI__c.field-meta.xml
<CustomField>
    <fullName>Svc_Type_Code_EI__c</fullName>
    <description>E  (Electric) or G  (Gas)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>E  (Electric) or G  (Gas)</inlineHelpText>
    <label>Service Type Code</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CARE_HistoryTabController.cls
/***********************************************************************************************************   
Apex Util class Name :  CARE_HistoryTabController
Version              :  1.0                                                                          
Created Date         :  05/14/2020                                                         
Function             :  This is the Apex Controller for history Tab of CARE Application Component.
Story                :                                                                               
Work Task            :                                                                               
Modification Log     :                                                                               
*----------------------------------------------------------------------------------------------------------  
* When                  Who                   								Description                                     
* ---------------------------------------------------------------------------------------------------------  
* 05/13/2020            Cognizant Technology Solutions                     Initial Version.
*                                                                          CARE Application: 
****************************************************************************************************************************************/

public with sharing class CARE_HistoryTabController {
    
    //Wrapper class for History List
    Public class HistoryListWrapper{
        @AuraEnabled
        public String sApplicationName {get; set;}
        @AuraEnabled
        public String sIdTable {get;set;}
        @AuraEnabled
        public String sId {get;set;}
        @AuraEnabled
        public String sSAID {get;set;}
        @AuraEnabled
        public String sSAType {get;set;}
        @AuraEnabled
        public String sDiscountType {get;set;}
        @AuraEnabled
        public Date dStartDate {get;set;}
        @AuraEnabled
        public Date dEndDate {get;set;}
        @AuraEnabled
        public Date dReceiveDate {get;set;}
        @AuraEnabled
        public String sContact {get;set;}
        @AuraEnabled
        public String sDescription {get;set;}
        @AuraEnabled
        public String sCCBComment {get;set;}
        @AuraEnabled
        public String sTypeNo {get;set;}
        @AuraEnabled
        public String sAppSource {get;set;}
        @AuraEnabled
        public String sCommittedBy {get;set;}
        @AuraEnabled
        public String sFormatText {get;set;}
        @AuraEnabled
        public String sViewButton {get;set;}
        @AuraEnabled
        public Boolean bDeleteButton {get;set;}
        @AuraEnabled
        public String sApplicationStatus {get;set;}

    }
    public class TotalHistoryWrapper{
       @AuraEnabled
       public List<HistoryListWrapper> listHistoryWrapper {get;set;}
        @AuraEnabled
       public Integer iTotalRecCount {get;set;}
        @AuraEnabled
       public Id idLastRec {get;set;}
    }
    
    //method to get the CARE app enrollment history details to whow under history tab 
    @AuraEnabled(Cacheable = true)
    public static TotalHistoryWrapper getEnrollHistoryData (String sPerID, String sMakeLiveCall, String recordId){
        
        TotalHistoryWrapper totHistoryRecords = new TotalHistoryWrapper();
        
        List<HistoryListWrapper> listHistoryRecords = new List<HistoryListWrapper>();
		List<CARE_Application__c> listcareAppRecordsNList = new list<CARE_Application__c>();        
        Date dTodaysDate = Date.today();
        Date dDateBeforeTwoYears = dTodaysDate.addYears(-2);
        Integer iLimit = integer.valueof(CARE_Constants.CARE_History_QueryLimit);
        
        try{
            if(String.isBlank(recordId)){
                listcareAppRecordsNList = [SELECT ID,NAME, APPLICATION_STATUS__c, RECEIVED_DATE__c, PROCESSED_DATE__c, CARE_CI_CC__r.DESCR254__c,
                                                          CCB_CONTACT_CODE__c, CCB_CONTACT_CODE2__c, CCB_CONTACT_DESC__c, CCB_Contact_Type_No__c, CCB_CONTACT_DESC2__c,
                                                          CARE_CI_CC__r.USER_ID__c,SOURCE_CHANNEL_TYPE__c, CreatedDate,
                                                          (SELECT SA_ID__c, START_DATE__c, END_DATE__c , Service_Agreement__r.Svc_Type_Code_EI__c,
                                                           APPLICATION__c, RETRO_START_DATE__c, RETRO_END_DATE__c, CC_CL_CD__c, CCB_CONTACT_TYPE__c  FROM CARE_App_Enrolled_SA__r)
                                                          FROM CARE_Application__c WHERE PER_ID__C =: sPerID ORDER BY CreatedDate DESc, Id desc limit: iLimit];
                
                system.debug('listcareAppRecordsNList for blank record Id---->' + listcareAppRecordsNList.size());
            }
            else if(String.isNotBlank(recordId)){
                listcareAppRecordsNList = [SELECT ID,NAME, APPLICATION_STATUS__c, RECEIVED_DATE__c, PROCESSED_DATE__c, CARE_CI_CC__r.DESCR254__c,
                                                          CCB_CONTACT_CODE__c, CCB_CONTACT_CODE2__c, CCB_CONTACT_DESC__c, CCB_Contact_Type_No__c, CCB_CONTACT_DESC2__c,
                                                          CARE_CI_CC__r.USER_ID__c,SOURCE_CHANNEL_TYPE__c, CreatedDate,
                                                          (SELECT SA_ID__c, START_DATE__c, END_DATE__c , Service_Agreement__r.Svc_Type_Code_EI__c,
                                                           APPLICATION__c, RETRO_START_DATE__c, RETRO_END_DATE__c, CC_CL_CD__c, CCB_CONTACT_TYPE__c  FROM CARE_App_Enrolled_SA__r)
                                                          FROM CARE_Application__c WHERE PER_ID__C =: sPerID and Id <: recordId ORDER BY CreatedDate DESc, Id desc limit: iLimit];
                
                system.debug('listcareAppRecordsNList for non blank record Id---->' + listcareAppRecordsNList.size());
            }
            
           
            for( CARE_Application__c listcareAppRecords :listcareAppRecordsNList ){
                
                if (listcareAppRecords.CARE_App_Enrolled_SA__r != null && listcareAppRecords.CARE_App_Enrolled_SA__r.size()>0)
                {   integer cnt = 0; 
                    for (CARE_App_Enrolled_SA__C listCareEnrolledRecords : listcareAppRecords.CARE_App_Enrolled_SA__r)
                    {
                        HistoryListWrapper objRec = new HistoryListWrapper ();
                        objRec.sApplicationName = listcareAppRecords.Name;
                        objRec.sId =  listcareAppRecords.ID;
                        objRec.sIdTable =  listcareAppRecords.ID + '@@@' + cnt;
                        objRec.dReceiveDate = listcareAppRecords.PROCESSED_DATE__c == null ? listcareAppRecords.RECEIVED_DATE__c : listcareAppRecords.PROCESSED_DATE__c;
                        objRec.sDiscountType = listCareEnrolledRecords.CC_CL_CD__c; //listcareAppRecords.CC_CL_CD__c;
                        objRec.sDescription =  listcareAppRecords.CCB_CONTACT_DESC2__c == null ? listcareAppRecords.CCB_CONTACT_DESC__c : listcareAppRecords.CCB_CONTACT_DESC2__c;                        
                        objRec.sContact =  listcareAppRecords.CCB_CONTACT_CODE2__c == null? listcareAppRecords.CCB_CONTACT_CODE__c : listcareAppRecords.CCB_CONTACT_CODE2__c; 
                        objRec.sCCBComment =  listcareAppRecords.CARE_CI_CC__r.DESCR254__c; 
                        objRec.sCommittedBy =  listcareAppRecords.CARE_CI_CC__r.USER_ID__c; 
                        objRec.sAppSource =  listcareAppRecords.SOURCE_CHANNEL_TYPE__c;  
                        objRec.sSAID = listCareEnrolledRecords.SA_ID__c;
                        objRec.sApplicationStatus = listcareAppRecords.APPLICATION_STATUS__c;
                        objRec.sSAType = listCareEnrolledRecords.Service_Agreement__r.Svc_Type_Code_EI__c;
                        objRec.dStartDate = listCareEnrolledRecords.RETRO_START_DATE__C == null? listCareEnrolledRecords.START_DATE__c : listCareEnrolledRecords.RETRO_START_DATE__C; 
                        objRec.dEndDate = listCareEnrolledRecords.END_DATE__c;
                        objRec.sTypeNo = listcareAppRecords.CCB_Contact_Type_No__c != '' ? listcareAppRecords.CCB_Contact_Type_No__c : ''; 
                        //objRec.dEndDate = listCareEnrolledRecords.RETRO_END_DATE__c == null? listCareEnrolledRecords.SA_END_DATE__c : listCareEnrolledRecords.RETRO_END_DATE__c;
                        //format text based on the created date
                        objRec.sFormatText = listcareAppRecords.CreatedDate >= dDateBeforeTwoYears ? 'slds-text-title_bold':'slds-text-color_weak';
                        //set view button visiblity --Commented code as per Demo1 feedback
                        objRec.sViewButton = 'slds-show';
                        // --Commented code as per Demo1 feedback
                        //objRec.sViewButton = listcareAppRecords.SOURCE_CHANNEL_TYPE__c != 'Batch'?'slds-show':'slds-hide';
                        if(listcareAppRecords.APPLICATION_STATUS__c == 'Staged for CC&B' || listcareAppRecords.APPLICATION_STATUS__c == 'Sent to CC&B' ||
                           listcareAppRecords.APPLICATION_STATUS__c == 'Reconciled' || listcareAppRecords.APPLICATION_STATUS__c == 'Completed')
                        {
                            objRec.bDeleteButton = true;
                        }
                        else{
                            objRec.bDeleteButton = false;
                        }                                               
                        listHistoryRecords.add(objRec);
                        cnt++;
                    }
                } 
                else {
                    HistoryListWrapper objRec = new HistoryListWrapper ();
                    objRec.sApplicationName = listcareAppRecords.Name;
                    objRec.sId =  listcareAppRecords.ID;
                    objRec.sIdTable =  listcareAppRecords.ID;
                    objRec.dReceiveDate = listcareAppRecords.PROCESSED_DATE__c == null ? listcareAppRecords.RECEIVED_DATE__c : listcareAppRecords.PROCESSED_DATE__c;
                    objRec.sDescription =  listcareAppRecords.CCB_CONTACT_DESC2__c == null ? listcareAppRecords.CCB_CONTACT_DESC__c : listcareAppRecords.CCB_CONTACT_DESC2__c;              
                    objRec.sContact =  listcareAppRecords.CCB_CONTACT_CODE2__c == null? listcareAppRecords.CCB_CONTACT_CODE__c : listcareAppRecords.CCB_CONTACT_CODE2__c;  
                    objRec.sTypeNo = listcareAppRecords.CCB_Contact_Type_No__c != '' ? listcareAppRecords.CCB_Contact_Type_No__c : ''; 
                    objRec.sCCBComment =  listcareAppRecords.CARE_CI_CC__r.DESCR254__c; 
                    objRec.sCommittedBy =  listcareAppRecords.CARE_CI_CC__r.USER_ID__c; 
                    objRec.sAppSource =  listcareAppRecords.SOURCE_CHANNEL_TYPE__c;  
                    objRec.sApplicationStatus = listcareAppRecords.APPLICATION_STATUS__c;
                    //format text based on the created date
                    objRec.sFormatText = listcareAppRecords.CreatedDate >= dDateBeforeTwoYears ? 'slds-text-title_bold':'slds-text-color_weak';
                    //set view button visiblity
                    objRec.sViewButton = 'slds-show';
                    // --Commented code as per Demo1 feedback
                    // objRec.sViewButton = listcareAppRecords.SOURCE_CHANNEL_TYPE__c != 'Batch'?'slds-show':'slds-hide';
                    if(listcareAppRecords.APPLICATION_STATUS__c == 'Staged for CC&B' || listcareAppRecords.APPLICATION_STATUS__c == 'Sent to CC&B' ||
                       listcareAppRecords.APPLICATION_STATUS__c == 'Reconciled' || listcareAppRecords.APPLICATION_STATUS__c == 'Completed')
                    {
                        objRec.bDeleteButton = true;
                    }
                    else{objRec.bDeleteButton = false;}
                    listHistoryRecords.add(objRec);     
                    
                }
                 Integer iCountTotal =  [SELECT count() FROM Care_Application__c WHERE PER_ID__C =: sPerID];

                totHistoryRecords.listHistoryWrapper = listHistoryRecords;
                totHistoryRecords.iTotalRecCount = iCountTotal;
                totHistoryRecords.idLastRec = listcareAppRecordsNList[listcareAppRecordsNList.size()-1].Id;
            }
            }catch(Exception ex){
            
            system.debug(ex.getLineNumber()+ ': >' + ex.getMessage() + ': >' + ex.getStackTraceString());
        }
        return  totHistoryRecords;
    }
    
    //method to Delete the Enrollment record
    @AuraEnabled
    public static void deleteEnrollmentRecord(String sEnrollmentId){        
        try{
            //Delete the images uploaded in ContentDocument as it has no master-detail relationship between Care_Application and ContentDocument
            //Hence explicitly delete the ContentDocument
            //For Care_App_Image_List, this will get automatically deleted when Care_Application gets deleted
            Boolean bDeletedSuccess = CARE_UtilityController.deleteUploadedContents(sEnrollmentId);
            
            if(bDeletedSuccess){
                CARE_Application__c[] rec = [SELECT Id FROM CARE_Application__c where Id =: sEnrollmentId];          
                delete rec;   
            }            
        }
        catch(Exception ex){
            system.debug(ex.getLineNumber()+ ': >' + ex.getMessage() + ': >' + ex.getStackTraceString());
        }
    }
    
    //method to show the special message for Msg button in History Tab
     @AuraEnabled(cacheable=true)
        public static string getSpecialMessage(String sApplicationNo, String sTypeNo)
    {
        String sSpecialMessage='';
        system.debug('CARE sApplicationNo----->'+sApplicationNo);
        system.debug('CARE sTypeNo----->'+sTypeNo);
        
        try{
            String scomments;
             CARE_Application__c careAppObj = [SELECT CCB_CONTACT_CODE__c, CC_CL_CD__c, PROCESSED_DATE__c 
                                              FROM CARE_Application__c WHERE Name =:sApplicationNo];
            
            if(string.isNotBlank(sTypeNo)){
                scomments=[SELECT COMMENTS__c FROM CARE_Type__c 
                         WHERE TYPE_NO__c =: sTypeNo limit 1].COMMENTS__c;
            }
            else{
              scomments=[SELECT COMMENTS__c FROM CARE_Type__c 
                         WHERE TYPE_CODE__c=:careAppObj.CCB_CONTACT_CODE__c LIMIT 1].COMMENTS__c;
            }
             system.debug('scomments is----->'+scomments);
            if(string.isNotBlank(scomments)){
                if(scomments.contains(CARE_Constants.CARE_DISCOUNT_TYPE_PLACEHOLDER)){
                    sSpecialMessage = scomments.replace(CARE_Constants.CARE_DISCOUNT_TYPE_PLACEHOLDER, careAppObj.CC_CL_CD__c);
             		//sSpecialMessage = scomments.replace(CARE_Constants.CARE_CC_DATE_PLACEHOLDER, careAppObj.PROCESSED_DATE__c.format());
                }
                else if(scomments.contains(CARE_Constants.CARE_CC_DATE_PLACEHOLDER)){
                    sSpecialMessage = scomments.replace(CARE_Constants.CARE_CC_DATE_PLACEHOLDER, careAppObj.PROCESSED_DATE__c.format());
                } 
                else if(scomments.contains(CARE_Constants.CARE_DISCOUNT_TYPE_PLACEHOLDER) && scomments.contains(CARE_Constants.CARE_CC_DATE_PLACEHOLDER)){
                    scomments = scomments.replace(CARE_Constants.CARE_DISCOUNT_TYPE_PLACEHOLDER, careAppObj.CC_CL_CD__c);
                    sSpecialMessage = scomments.replace(CARE_Constants.CARE_CC_DATE_PLACEHOLDER, careAppObj.PROCESSED_DATE__c.format());
                }
                else{
                    sSpecialMessage = scomments;
                }
            }
            else{
             sSpecialMessage = CARE_Constants.CARE_NO_SPECIAL_MSG;
            }
            system.debug('sSpecialMessage is----->'+sSpecialMessage);
        }
          catch(Exception ex){
          system.debug(ex.getLineNumber()+ ': >' + ex.getMessage() + ': >' + ex.getStackTraceString());
        }
        return sSpecialMessage;
    }
}