force-app/main/default/objects/CARE_App_Enrolled_SA__c/CARE_App_Enrolled_SA__c.object-meta.xml
<CustomObject>
    <description>SA(s) affected by the transaction in the CARE Application object</description>
    <label>CARE App Enrolled SA</label>
    <nameField>
        <displayFormat>CTSA{000000000}</displayFormat>
        <label>NAME  (APP SA Seq)</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE App Enrolled SA</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/APPLICATION__c.field-meta.xml
<CustomField>
    <fullName>APPLICATION__c</fullName>
    <label>APPLICATION</label>
    <referenceTo>CARE_Application__c</referenceTo>
    <relationshipLabel>CARE App Enrolled SA</relationshipLabel>
    <relationshipName>CARE_App_Enrolled_SA</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/CARE_CC_BATCH_DETAIL__c.field-meta.xml
<CustomField>
    <fullName>CARE_CC_BATCH_DETAIL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CARE CC BATCH DETAIL</label>
    <referenceTo>CARE_CC_Batch_Detail__c</referenceTo>
    <relationshipLabel>CARE App Enrolled SA</relationshipLabel>
    <relationshipName>CARE_App_Enrolled_SA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/PER_ID__c.field-meta.xml
<CustomField>
    <fullName>PER_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PER ID</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/PREM_ID__c.field-meta.xml
<CustomField>
    <fullName>PREM_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PREM ID</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/CARE_CC_Batch_Detail__c.object-meta.xml
<CustomObject>
    <description>CARE CC Batch Detail</description>
    <label>CARE CC Batch Detail</label>
    <nameField>
        <displayFormat>CCD{0000000000}</displayFormat>
        <label>Name(Sequence No)</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE CC Batch Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/APPLICATION__c.field-meta.xml
<CustomField>
    <fullName>APPLICATION__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>APPLICATION</label>
    <referenceTo>CARE_Application__c</referenceTo>
    <relationshipLabel>CARE CC Batch Detail</relationshipLabel>
    <relationshipName>CARE_CC_Batch_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/CARE_APP_ENROLLED_SA__c.field-meta.xml
<CustomField>
    <fullName>CARE_APP_ENROLLED_SA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CARE APP ENROLLED SA</label>
    <referenceTo>CARE_App_Enrolled_SA__c</referenceTo>
    <relationshipLabel>CARE CC Batch Detail</relationshipLabel>
    <relationshipName>CARE_CC_Batch_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/CARE_CI_CC__c.field-meta.xml
<CustomField>
    <fullName>CARE_CI_CC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CARE CI CC</label>
    <referenceTo>CARE_CI_CC__c</referenceTo>
    <relationshipLabel>CARE CC Batch Detail</relationshipLabel>
    <relationshipName>CARE_CC_Batch_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/CC_TYPE_CD__c.field-meta.xml
<CustomField>
    <fullName>CC_TYPE_CD__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CC TYPE CD</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_CI_CC__c/CARE_CI_CC__c.object-meta.xml
<CustomObject>
    <description>CARE CI CC data from CC&amp;B</description>
    <label>CARE CI CC</label>
    <nameField>
        <displayFormat>CICC{0000000000}</displayFormat>
        <label>Sequence No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE CI CC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_CI_CC__c/fields/CC_DTTM__c.field-meta.xml
<CustomField>
    <fullName>CC_DTTM__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CC DTTM</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_CI_CC__c/fields/PER_ID__c.field-meta.xml
<CustomField>
    <fullName>PER_ID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>PER ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_System_Value__c/CARE_System_Value__c.object-meta.xml
<CustomObject>
    <description>Object to store system configuration values</description>
    <label>CARE System Value</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>NAME</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE System Value</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_System_Value__c/fields/SYSTEM_VALUE__c.field-meta.xml
<CustomField>
    <fullName>SYSTEM_VALUE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SYSTEM VALUE</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CARE_System_Value__c/fields/SYSTEM_VALUE_CODE__c.field-meta.xml
<CustomField>
    <fullName>SYSTEM_VALUE_CODE__c</fullName>
    <externalId>true</externalId>
    <label>SYSTEM VALUE CODE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CARE_ESAFortyFiveDayExpireBatch.cls
/**************************************************************************************************   
Apex Batch Name      :  CARE_ESAFortyFiveDayExpireBatch
Version              :  1.0                                                                          
Created Date         :  07/30/2020                                                              
Function             :  This batch class is invoked to check if customer is not ESA enrolled 
                        after 45 days of H RAND CERT cc code stamp.
Story                :                                                                               
Work Task            :                                                                            
Modification Log     :                                                                            
*--------------------------------------------------------------------------------------------------  
* Developer                 Date                   Description                                     
* -------------------------------------------------------------------------------------------------  
* A8AI                   07/30/2020                First Iteration  

***************************************************************************************************/

global class CARE_ESAFortyFiveDayExpireBatch implements Database.Batchable<sObject>,Database.Stateful{
    
    global Integer iSystemValue = 0;
    global Date dTodaysDate = Date.today();
    global Date dFortyFiveDay;
    global Date dDateTwoYearsBefore;
    global Integer recordsProcessed = 0;
    global Set<Id> setDropAppIdESA = new Set<Id>();
    global Set<Id> setDropErrorIdESA = new Set<Id>();
    global Set<String> setDropErrorPerIdESA = new Set<String>();
    global String sESACodeExpire = CARE_Constants.CARE_CC_ESA_ENROLLMENTCHECK;

    
    /**
    * Method name  : start
    * Description  : Querying all records to check ESA enrollment after 45 days.
    * Return Type  : Database.QueryLocator
    * Parameter    : Database.BatchableContext
    **/
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        List<CARE_System_Value__c> listGetSystemValue = new List<CARE_System_Value__c>();
        List<Integer> listCareSystemValue = new List<Integer>{CARE_Constants.CARE_ESA_SystemValueCode};
        listGetSystemValue = CARE_UtilityController.getCareSystemValue(listCareSystemValue);
            
            if(listGetSystemValue.size() > 0){
                for(CARE_System_Value__c careSystemRecord : listGetSystemValue){
                    if(careSystemRecord.SYSTEM_VALUE_CODE__c == CARE_Constants.CARE_ESA_SystemValueCode){
                        iSystemValue = Integer.valueOf(careSystemRecord.SYSTEM_VALUE__c); 
                    }
                } 
            }else{
                iSystemValue = CARE_Constants.CARE_FortyFiveDay;
            }
        
        dFortyFiveDay = dTodaysDate.addDays(-iSystemValue);
        dDateTwoYearsBefore = dFortyFiveDay.addDays(-CARE_Constants.CARE_BeforeTwoYearsInDays);
        system.debug('dFortyFiveDay--->'+dFortyFiveDay);
        system.debug('dDateTwoYearsBefore--->'+dDateTwoYearsBefore);
        
        String query = 'SELECT APPLICATION__c, PER_ID__c, CARE_APP_ENROLLED_SA__r.PREM_ID__c from CARE_CC_Batch_Detail__c where CARE_CI_CC__r.CC_TYPE_CD__c =: sESACodeExpire AND CARE_CI_CC__r.CC_DTTM__c <=: dFortyFiveDay AND CARE_CI_CC__r.CC_DTTM__c >=: dDateTwoYearsBefore';
        system.debug('query---->'+query);
        return Database.getQueryLocator(query);
            /*'SELECT APPLICATION__c, PER_ID__c, CARE_APP_ENROLLED_SA__r.PREM_ID__c from CARE_CC_Batch_Detail__c' +
            'where CARE_CI_CC__r.CC_TYPE_CD__c =: CARE_Constants.CARE_CC_ESA_ENROLLMENTCHECK' + 
            'AND CARE_CI_CC__r.CC_DTTM__c <=: dFortyFiveDay AND CARE_CI_CC__r.CC_DTTM__c >=: dDateTwoYearsBefore'
        );*/
        
    }
    
    /**
    * Method name  : execute
    * Description  : this method will execute validations to check customer has been enrolled in ESA or not
    *                and subsequently create transaction records
    * Return Type  : void
    * Parameter    : Database.BatchableContext, List<sObject>
    **/
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        
        system.debug('inside execute method----->');
        recordsProcessed+=scope.size();
        
        List<CARE_CC_Batch_Detail__c> listHRandCert = (List<CARE_CC_Batch_Detail__c>)scope;
        System.debug('listHRandCert---> '+listHRandCert);
        system.debug('listHRandCert size--->'+listHRandCert.size());
        CARE_AutoUtilityController.ESAThresholdCheckWrapper WrapperResponse = new CARE_AutoUtilityController.ESAThresholdCheckWrapper();
        
        if(listHRandCert.size() > 0){
           WrapperResponse = CARE_AutoUtilityController.notEnrolledESADropCustomers(listHRandCert);
            if(WrapperResponse.setESADropAppId.size() > 0){
                for(Id recId : WrapperResponse.setESADropAppId){
                    setDropAppIdESA.add(recId); 
                }
            }
            if(WrapperResponse.setESADropErrId.size() > 0){
                for(Id recId : WrapperResponse.setESADropErrId){
                    setDropErrorIdESA.add(recId); 
                }
            }
            if(WrapperResponse.setESADropErrPerId.size() > 0){
                for(String perId : WrapperResponse.setESADropErrPerId){
                    setDropErrorPerIdESA.add(perId); 
                }
            }
        }
    }
    
    /**
    * Method name  : finish
    * Description  : this method holds all the success and drop records
    * Return Type  : void
    * Parameter    : Database.BatchableContext 
    **/
    global void finish(Database.BatchableContext BC) {
        
        system.debug('All fail ESA Drop Ids===' +setDropErrorIdESA);
        system.debug('All failed ESA Drop per Id===' +setDropErrorPerIdESA);
        system.debug('All success ESA Drop Id---' +setDropAppIdESA);
    }
    

}