force-app/main/default/objects/EI_ApexClassCatelog__c/EI_ApexClassCatelog__c.object-meta.xml
<CustomObject>
    <label>EI ApexClassCatelog</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>Process Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EI_ApexClassCatelog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EI_ApexClassCatelog__c/fields/FileNameRegex__c.field-meta.xml
<CustomField>
    <fullName>FileNameRegex__c</fullName>
    <description>Data file naming pattern in Regex</description>
    <encryptionScheme>None</encryptionScheme>
    <label>FileName Regex</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EI_ApexParameter__c/EI_ApexParameter__c.object-meta.xml
<CustomObject>
    <label>EI ApexParameter</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EI ApexParameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/EI_ApexParameter__c/fields/EI_ApexClassCatelog__c.field-meta.xml
<CustomField>
    <fullName>EI_ApexClassCatelog__c</fullName>
    <label>EI ApexClassCatelog</label>
    <referenceTo>EI_ApexClassCatelog__c</referenceTo>
    <relationshipLabel>EI ApexParameters</relationshipLabel>
    <relationshipName>EI_ApexParameters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EI_ApexParameter__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Value</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CARE_LoadUserFile.cls
public class CARE_LoadUserFile {
   @AuraEnabled 
   public static String getParameters (String argFileName, String argDocId, String fileSearchKey) {
       
       string sFileName = fileSearchKey;
       system.debug('@@@@@@fileSearchKey' + fileSearchKey);       
       string soqlQuery = 'select name, value__c from EI_ApexParameter__c where EI_ApexClassCatelog__r.Category__c = ' + '\'CARE.USERLOAD\' and EI_ApexClassCatelog__r.FileNameRegex__c like \'%' + sFileName + '%\''; 
       system.debug('@@@soqlQuery' + soqlQuery);
       List<EI_ApexParameter__c> listParm = Database.query(soqlQuery); 
       EI_BulkLoad.BulkUploadWrapper blkArg = new EI_BulkLoad.BulkUploadWrapper();
       system.debug('@@@@@@loaduser' + listParm);
       for(EI_ApexParameter__c parm :listParm){
           switch on parm.name {
               when 'objectApi' {		
                   blkArg.objectAPI = parm.value__c;
               }	
               when 'reqFields' {
                   blkArg.reqFields = (String[])JSON.deserialize(parm.value__c, String[].class);
               }
               when 'dmlAction' {		
                   blkArg.dmlAction = parm.value__c;
               }
               when 'csvFieldMap' {		
                   blkArg.csvFieldMap = (EI_BulkLoad.FieldMapSection[])JSON.deserialize(parm.value__c, EI_BulkLoad.FieldMapSection[].class);
               }	
               when 'parmList' {
                   blkArg.parmList = (EI_BulkLoad.ParmSection[])JSON.deserialize(parm.value__c , EI_BulkLoad.ParmSection[].class);
               }
               when 'className' {		
                   blkArg.className = parm.value__c;
               }
               when 'libraryName' {		
                   blkArg.libraryName = parm.value__c;
               }
               when 'storeSourceFile' {		
                   blkArg.storeSourceFile = (parm.value__c == 'true')?Boolean.valueOf(parm.value__c):false;
               }
               when 'batchSize' {		
                   blkArg.batchSize = (parm.value__c !='')?Integer.valueOf(parm.value__c):200;
               }
               when 'tgtArg' {		
                   blkArg.tgtArg = parm.value__c;
               }
           }
       }
       
       blkArg.csvFileName     = argFileName;
       blkArg.documentId      = argDocId;
       String jsonReturn = JSON.serialize(blkArg);
       system.debug('@@@@jsonReturn' + jsonReturn);
       return jsonReturn;
   } 
}