force-app/main/default/objects/CARE_Batch_Staging__c/CARE_Batch_Staging__c.object-meta.xml
<CustomObject>
    <label>CARE Batch Staging</label>
    <nameField>
        <displayFormat>CBS-{000000000}</displayFormat>
        <label>Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE Batch Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_Batch_Staging__c/fields/APPLICANT_NAME__c.field-meta.xml
<CustomField>
    <fullName>APPLICANT_NAME__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>APPLICANT NAME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Batch_Staging__c/fields/CARE_BILLING_ACCT_ID__c.field-meta.xml
<CustomField>
    <fullName>CARE_BILLING_ACCT_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>BILLING ACCT ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Batch_Staging__c/fields/EI_ACCOUNT__c.field-meta.xml
<CustomField>
    <fullName>EI_ACCOUNT__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EI ACCOUNT</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CARE Batch Staging</relationshipLabel>
    <relationshipName>CARE_Batch_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_Batch_Staging__c/fields/JOB_NO__c.field-meta.xml
<CustomField>
    <fullName>JOB_NO__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>JOB NO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Batch_Staging__c/fields/PER_ID__c.field-meta.xml
<CustomField>
    <fullName>PER_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PER ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Batch_Staging__c/fields/Processing_Message__c.field-meta.xml
<CustomField>
    <fullName>Processing_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Processing Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Batch_Staging__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <defaultValue>&quot;Loaded&quot;</defaultValue>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loaded</fullName>
                <default>true</default>
                <label>Loaded</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Batch_Staging__c/fields/Source_Channel_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Channel_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Source Channel Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CARE_ManualUpload.cls
/***********************************************************************************************************   
Apex Batch Class Name :  CARE_ManualUpload
Version               :  1.0                                                                          
Created Date          :  08/13/2020
Function              :  This is the apex class to process Manual uploads for V code and VH code.
Story                 :                                                                               
Work Task             :                                                                               
Modification Log      :                                                                               
*----------------------------------------------------------------------------------------------------------  
* When                  Who                    Description                                     
* ---------------------------------------------------------------------------------------------------------  
* 08/13/2020            A8AI                   Initial Version.
*                                              CARE Application: 
****************************************************************************************************************************************/

global class CARE_ManualUpload{
    
    public Class processVCode implements DynamicApex.DynamicApexInterface {
        
        public String execute(String arg) {
            System.debug('MyClassName Class Runs with arg = ' + arg);
            //String jsonReturn;
            //Map<String, Object> responseObj = new Map<String, Object>();
            Map<String, Set<Id>> responseObjMap = new Map<String, Set<Id>>();
            String jobNo = 'CBJ-0016';
            DynamicApex.returnWrapper rtnJSON = new DynamicApex.returnWrapper();
            try{
            
            CARE_AutoUtilityController.stampVCodeWrapper WrapperResponse = new CARE_AutoUtilityController.stampVCodeWrapper();
            
            List<CARE_Batch_Staging__c> listOfVCodeRecords = new List<CARE_Batch_Staging__c>();
            
            listOfVCodeRecords = CARE_ManualUpload.getRecordsForManualLoad(jobNo);
            
            if(listOfVCodeRecords.size() > 0){
                WrapperResponse = CARE_AutoUtilityController.determineVCodeStamping(listOfVCodeRecords);
                responseObjMap.put('processVCode Runs with arg = ', WrapperResponse.careAppSet);
                responseObjMap.put('processVCode Runs with arg = ', WrapperResponse.careAppErrorIdSet);
                
            	rtnJSON.returnCode     = 1;
            	rtnJSON.message        = 'Operation Completed';
            	rtnJSON.requestSuccess = 'true';
            	rtnJSON.data           = 'processVCode Runs with arg = ' + responseObjMap;
            	//return JSON.serialize(rtnJSON);
                //jsonReturn = JSON.serialize(rtnJSON);
            }
            else{
                rtnJSON.returnCode     = 1;
            	rtnJSON.message        = 'Operation Failed';
            	rtnJSON.requestSuccess = 'false';
            	rtnJSON.data           = 'No Records Founds with arg = ' + responseObjMap;
            	//return JSON.serialize(rtnJSON);
                //jsonReturn = JSON.serialize(rtnJSON);
            }
        }catch(DmlException ex) 
            {
                    rtnJSON.message    = 'Operation Failed';
                    rtnJSON.requestSuccess = 'false'; 
                    EI_CreateErrorLog.upsertException(EI_CreateErrorLog.logException('EI API runtime error: ' , new EI_BatchException(ex.getMessage())));
                    CARE_UtilityController.sendExceptionEmail('CARE_ManualUpload', '', '', '', ex);
            }           
            String jsonReturn = JSON.serialize(rtnJSON);
            return  jsonReturn;           
        }
        
    }
    
    public Class processVHCode implements DynamicApex.DynamicApexInterface {
        
        public String execute(String arg) {
            System.debug('MyClassName Class Runs with arg = ' + arg);
            //String jsonReturn;
            //Map<String, Object> responseObj = new Map<String, Object>();
            String jobNo = 'CBJ-0017';
            Map<String, Set<Id>> responseObjMap = new Map<String, Set<Id>>();
            DynamicApex.returnWrapper rtnJSON = new DynamicApex.returnWrapper();
            try{
            
            CARE_AutoUtilityController.StampVHCodeWrapper WrapperResponseVH = new CARE_AutoUtilityController.StampVHCodeWrapper();
            
            List<CARE_Batch_Staging__c> listOfVHCodeRecords = new List<CARE_Batch_Staging__c>();
            
            listOfVHCodeRecords = CARE_ManualUpload.getRecordsForManualLoad(jobNo);
            
            if(listOfVHCodeRecords.size() > 0){
                WrapperResponseVH = CARE_AutoUtilityController.determineVHCodeStamping(listOfVHCodeRecords);
                responseObjMap.put('processVHCode Runs with arg = ', WrapperResponseVH.careAppSet);
                responseObjMap.put('processVHCode Runs with arg = ', WrapperResponseVH.careAppErrorIdSet);
                
            	rtnJSON.returnCode     = 1;
            	rtnJSON.message        = 'Operation Completed';
            	rtnJSON.requestSuccess = 'true';
            	rtnJSON.data           = 'processVCode Runs with arg = ' + responseObjMap;
            	//return JSON.serialize(rtnJSON);
                //jsonReturn = JSON.serialize(rtnJSON);
            }
            else{
                rtnJSON.returnCode     = 1;
            	rtnJSON.message        = 'Operation Failed';
            	rtnJSON.requestSuccess = 'false';
            	rtnJSON.data           = 'No Records Founds with arg = ' + responseObjMap;
            	//return JSON.serialize(rtnJSON);
                //jsonReturn = JSON.serialize(rtnJSON);
            }
        }catch(DmlException ex) 
            {
                    rtnJSON.message    = 'Operation Failed';
                    rtnJSON.requestSuccess = 'false'; 
                    EI_CreateErrorLog.upsertException(EI_CreateErrorLog.logException('EI API runtime error: ' , new EI_BatchException(ex.getMessage())));
                    CARE_UtilityController.sendExceptionEmail('CARE_ManualUpload', '', '', '', ex);
            }           
            String jsonReturn = JSON.serialize(rtnJSON);
            return  jsonReturn;           
        }
        
    }
    
    private static List<CARE_Batch_Staging__c> getRecordsForManualLoad(String jobNumber){
        
       List<CARE_Batch_Staging__c> listManualLoadRecords = new List<CARE_Batch_Staging__c>();
       
        try{
       listManualLoadRecords = [SELECT Id, PER_ID__c, JOB_NO__c, APPLICANT_NAME__c, CARE_BILLING_ACCT_ID__c, EI_ACCOUNT__c, 
                                Processing_Message__c, Processing_Status__c, Source_Channel_Type__c
                                 FROM CARE_Batch_Staging__c WHERE Processing_Status__c =: CARE_Constants.CARE_PROCESSING_LOADED AND JOB_NO__c =: jobNumber];
        
        }catch(DmlException ex) 
            {
                 EI_CreateErrorLog.upsertException(EI_CreateErrorLog.logException('EI API runtime error: ' , new EI_BatchException(ex.getMessage())));
                 CARE_UtilityController.sendExceptionEmail('CARE_ManualUpload', '', '', '', ex);
            } 
        
        return listManualLoadRecords;
    }


}