force-app/main/default/objects/CARE_CC_Batch_Detail__c/CARE_CC_Batch_Detail__c.object-meta.xml
<CustomObject>
    <description>CARE CC Batch Detail</description>
    <label>CARE CC Batch Detail</label>
    <nameField>
        <displayFormat>CCD{0000000000}</displayFormat>
        <label>Name(Sequence No)</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE CC Batch Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/CARE_CI_CC__c.field-meta.xml
<CustomField>
    <fullName>CARE_CI_CC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CARE CI CC</label>
    <referenceTo>CARE_CI_CC__c</referenceTo>
    <relationshipLabel>CARE CC Batch Detail</relationshipLabel>
    <relationshipName>CARE_CC_Batch_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/CC_CL_CD__c.field-meta.xml
<CustomField>
    <fullName>CC_CL_CD__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CC CL CD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/CC_TYPE_CD__c.field-meta.xml
<CustomField>
    <fullName>CC_TYPE_CD__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CC TYPE CD</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/DATE1__c.field-meta.xml
<CustomField>
    <fullName>DATE1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DATE1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/DATE2__c.field-meta.xml
<CustomField>
    <fullName>DATE2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DATE2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/DESCR254__c.field-meta.xml
<CustomField>
    <fullName>DESCR254__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DESCR254</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/SA_ID__c.field-meta.xml
<CustomField>
    <fullName>SA_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SA ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/SERVICE_TYPE_CODE__c.field-meta.xml
<CustomField>
    <fullName>SERVICE_TYPE_CODE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SERVICE TYPE CODE</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_CI_CC__c/CARE_CI_CC__c.object-meta.xml
<CustomObject>
    <description>CARE CI CC data from CC&amp;B</description>
    <label>CARE CI CC</label>
    <nameField>
        <displayFormat>CICC{0000000000}</displayFormat>
        <label>Sequence No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE CI CC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_CI_CC__c/fields/CC_DTTM__c.field-meta.xml
<CustomField>
    <fullName>CC_DTTM__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CC DTTM</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_CI_CC__c/fields/DESCR254__c.field-meta.xml
<CustomField>
    <fullName>DESCR254__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DESCR254</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CARE_CI_CC__c/fields/PER_ID__c.field-meta.xml
<CustomField>
    <fullName>PER_ID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>PER ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_CI_CC__c/fields/USER_ID__c.field-meta.xml
<CustomField>
    <fullName>USER_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>USER ID</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EI_Site__c/EI_Site__c.object-meta.xml
<CustomObject>
    <description>Sites are locations associated with Accounts, where work is performed.</description>
    <label>Site/Service Agreement</label>
    <nameField>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site/Service Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/EI_Site__c/fields/SAID_EI__c.field-meta.xml
<CustomField>
    <fullName>SAID_EI__c</fullName>
    <defaultValue>&quot;0000000000&quot;</defaultValue>
    <description>&apos;Service Agreement&apos; ID for the site.  Typically the electric meter number.</description>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <inlineHelpText>&apos;Service Agreement&apos; ID for the site.  Typically the electric meter number.</inlineHelpText>
    <label>SA ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EI_Site__c/fields/Svc_Type_Code_EI__c.field-meta.xml
<CustomField>
    <fullName>Svc_Type_Code_EI__c</fullName>
    <description>E  (Electric) or G  (Gas)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>E  (Electric) or G  (Gas)</inlineHelpText>
    <label>Service Type Code</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CARE_CCBHistoryController.cls
/***********************************************************************************************************   
Apex Util class Name :  CARE_CCBHistoryController
Version              :  1.0                                                                          
Created Date         :  05/19/2020                                                         
Function             :  This is the Apex Controller for CC&B History button of CARE Application Component.
Story                :                                                                               
Work Task            :                                                                               
Modification Log     :                                                                               
*----------------------------------------------------------------------------------------------------------  
* When                  Who                                                Description                                     
* ---------------------------------------------------------------------------------------------------------  
* 05/09/2020            Cognizant Technology Solutions                     Initial Version.
*                                                                          CARE Application: 
****************************************************************************************************************************************/
public class CARE_CCBHistoryController {
    
    @AuraEnabled(cacheable=true)
    
    public static List<DataTableWrapper> getCCBHistory(string sPerID){
        
        system.debug('sPerID----->' + sPerID);
        List<DataTableWrapper> response = new List<DataTableWrapper>();
        List<CARE_CC_Batch_Detail__c> resList = [select DATE1__c, DATE2__c,SA_ID__c,SERVICE_TYPE_CODE__c,CARE_CI_CC__r.DESCR254__c, CARE_CI_CC__r.CC_DTTM__c, CARE_CI_CC__r.CC_CL_CD__c, 
                                                 CARE_CI_CC__r.CC_TYPE_CD__c, CARE_CI_CC__r.USER_ID__c from CARE_CC_Batch_Detail__c where PER_ID__C =: sPerID];
        
        
        
        for(CARE_CC_Batch_Detail__c res : resList){            
            DataTableWrapper obj = new DataTableWrapper();
            obj.date1            = res.DATE1__c;
            obj.date2            = res.DATE2__c;
            obj.sa_id            = res.SA_ID__c;
            obj.descr            = res.CARE_CI_CC__r.DESCR254__c;
            obj.dttm             = res.CARE_CI_CC__r.CC_DTTM__c;
            obj.cl_cd            = res.CARE_CI_CC__r.CC_CL_CD__c;
            obj.cc_type_cd       = res.CARE_CI_CC__r.CC_TYPE_CD__c;
            obj.userid           = res.CARE_CI_CC__r.USER_ID__c;
            obj.sa_type          = res.SERVICE_TYPE_CODE__c;
            response.add(obj);
        }
        return response;
    }
 /* @AuraEnabled(Cacheable = true)
    public static List<DataTableWrapper> getSAType(){  
        List<DataTableWrapper> saType = new List<DataTableWrapper>();
        List<EI_Site__c> saTypeList = [SELECT Svc_Type_Code_EI__c from EI_Site__c where SAID_EI__c = '1243668790'];
        
        for(EI_Site__c sa : saTypeList){
            DataTableWrapper obj = new DataTableWrapper();
            obj.sa_type            = sa.Svc_Type_Code_EI__c;
            saType.add(obj);
        }
        return saType;  
    } */
    
    private class DataTableWrapper{
		@AuraEnabled
public Date date1 {get;set;}
        @AuraEnabled
public Date date2 {get;set;}
        @AuraEnabled
public String sa_id {get;set;}
        @AuraEnabled
public String descr {get;set;}
        @AuraEnabled
public Date dttm {get;set;}
        @AuraEnabled
public String cl_cd {get;set;}
        @AuraEnabled
public String cc_type_cd {get;set;}
        @AuraEnabled
public String userid {get;set;}
           @AuraEnabled
public String sa_type {get;set;}
    }
}