force-app/main/default/objects/CARE_CC_Batch_Detail__c/CARE_CC_Batch_Detail__c.object-meta.xml
<CustomObject>
    <description>CARE CC Batch Detail</description>
    <label>CARE CC Batch Detail</label>
    <nameField>
        <displayFormat>CCD{0000000000}</displayFormat>
        <label>Name(Sequence No)</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE CC Batch Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/CARE_CI_CC__c.field-meta.xml
<CustomField>
    <fullName>CARE_CI_CC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CARE CI CC</label>
    <referenceTo>CARE_CI_CC__c</referenceTo>
    <relationshipLabel>CARE CC Batch Detail</relationshipLabel>
    <relationshipName>CARE_CC_Batch_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/CC_TYPE_CD__c.field-meta.xml
<CustomField>
    <fullName>CC_TYPE_CD__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CC TYPE CD</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/CCB_Contact_Type_No__c.field-meta.xml
<CustomField>
    <fullName>CCB_Contact_Type_No__c</fullName>
    <description>Use the value in CARE_application</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB Contact Type No</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_CI_CC__c/CARE_CI_CC__c.object-meta.xml
<CustomObject>
    <description>CARE CI CC data from CC&amp;B</description>
    <label>CARE CI CC</label>
    <nameField>
        <displayFormat>CICC{0000000000}</displayFormat>
        <label>Sequence No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE CI CC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_CI_CC__c/fields/CC_DTTM__c.field-meta.xml
<CustomField>
    <fullName>CC_DTTM__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CC DTTM</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_CI_CC__c/fields/PER_ID__c.field-meta.xml
<CustomField>
    <fullName>PER_ID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>PER ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_System_Value__c/CARE_System_Value__c.object-meta.xml
<CustomObject>
    <description>Object to store system configuration values</description>
    <label>CARE System Value</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>NAME</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE System Value</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_System_Value__c/fields/SYSTEM_VALUE__c.field-meta.xml
<CustomField>
    <fullName>SYSTEM_VALUE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SYSTEM VALUE</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CARE_System_Value__c/fields/SYSTEM_VALUE_CODE__c.field-meta.xml
<CustomField>
    <fullName>SYSTEM_VALUE_CODE__c</fullName>
    <externalId>true</externalId>
    <label>SYSTEM VALUE CODE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CARE_System_Value__c/fields/SYSTEM_VALUE_TYPE__c.field-meta.xml
<CustomField>
    <fullName>SYSTEM_VALUE_TYPE__c</fullName>
    <label>SYSTEM_VALUE TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BATCH JOB</fullName>
            </value>
            <value>
                <fullName>CAREOPS</fullName>
            </value>
            <value>
                <fullName>CONTROL</fullName>
            </value>
            <value>
                <fullName>EMAIL</fullName>
            </value>
            <value>
                <fullName>RENEWAL MONTH</fullName>
            </value>
            <value>
                <fullName>SYSTEM</fullName>
            </value>
            <value>
                <fullName>URL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CARE_PEVFortyFiveDayBatch.cls
/**************************************************************************************************   
Apex Batch Name      :  CARE_PEVFortyFiveDayBatch
Version              :  1.0                                                                          
Created Date         :  07/30/2020                                                              
Function             :  This batch class is invoked to check if customer has responded with Income
documents within 45 daysof stamping V code.
Story                :                                                                               
Work Task            :                                                                            
Modification Log     :                                                                            
*--------------------------------------------------------------------------------------------------  
* Developer                 Date                   Description                                     
* -------------------------------------------------------------------------------------------------  
* A8AI                   07/30/2020                First Iteration  

***************************************************************************************************/

global class CARE_PEVFortyFiveDayBatch implements Database.Batchable<sObject>,Database.Stateful{
    
    global Integer iSystemValue = 0;
    global Date dTodaysDate = Date.today();
    global Date dFortyFiveDay;
    global Date dDateTwoYearsBefore;
    global Integer recordsProcessed = 0;
    global Set<Id> careAppPEVSet = new Set<Id>();
    global Set<Id> careAppErrorIdSet = new Set<Id>();
    global Set<String> setErrorPerId = new Set<String>();
    global String sVCode = CARE_Constants.CARE_CC_PEV;
    
    /**
* Method name  : start
* Description  : Querying all records which has V code stamped and not responding within 45 days.
* Return Type  : Database.QueryLocator
* Parameter    : Database.BatchableContext
**/
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        system.debug('inside start method----->');
        
        List<CARE_System_Value__c> listGetSystemValue = new List<CARE_System_Value__c>();
        List<Integer> listCareSystemValue = new List<Integer>();//{CARE_Constants.CARE_PEV_SystemValueCode};
        listCareSystemValue.add(CARE_Constants.CARE_PEV_SystemValueCode);
            system.debug('listCareSystemValue---->'+listCareSystemValue);
            if(listCareSystemValue.size() > 0){
            listGetSystemValue = CARE_UtilityController.getCareSystemValue(listCareSystemValue);
              system.debug('listGetSystemValue size if---->'+listGetSystemValue.size());
            }else{
               listGetSystemValue = [select SYSTEM_VALUE__c, SYSTEM_VALUE_CODE__c from CARE_System_Value__c where SYSTEM_VALUE_CODE__c = 810];
            system.debug('listGetSystemValue size else---->'+listGetSystemValue.size());
            }
        
        
        if(listGetSystemValue.size() > 0){
            for(CARE_System_Value__c careSystemRecord : listGetSystemValue){
                if(careSystemRecord.SYSTEM_VALUE_CODE__c == CARE_Constants.CARE_PEV_SystemValueCode){
                    iSystemValue = Integer.valueOf(careSystemRecord.SYSTEM_VALUE__c); 
                }else{
                    iSystemValue = CARE_Constants.CARE_FortyFiveDay;
                }
            } 
        }else{
           iSystemValue = CARE_Constants.CARE_FortyFiveDay; 
        }
        dFortyFiveDay = dTodaysDate.addDays(-iSystemValue);
        dDateTwoYearsBefore = dFortyFiveDay.addDays(-CARE_Constants.CARE_BeforeTwoYearsInDays);
        
        String query = 'SELECT ID, PER_ID__c, CCB_Contact_Type_No__c, CARE_CI_CC__r.CC_TYPE_CD__c, CARE_CI_CC__r.CC_DTTM__c from CARE_CC_Batch_Detail__c Where CARE_CI_CC__r.CC_TYPE_CD__c =: sVCode AND CARE_CI_CC__r.CC_DTTM__c <=: dFortyFiveDay AND CARE_CI_CC__r.CC_DTTM__c >=: dDateTwoYearsBefore';
        
        return Database.getQueryLocator(query);
          
    }
    
    /**
* Method name  : execute
* Description  : this method will execute validations to check if person Id has responded after V code stamping
* Return Type  : void
* Parameter    : Database.BatchableContext, List<sObject>
**/
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        
        system.debug('inside execute method----->');
        recordsProcessed = scope.size();
        List<CARE_CC_Batch_Detail__c> listOfVCode = (List<CARE_CC_Batch_Detail__c>)scope;
        CARE_AutoUtilityController.PEVResponseCheckWrapper WrapperResponse = new CARE_AutoUtilityController.PEVResponseCheckWrapper();
        
        system.debug('listOfVCode size--->'+listOfVCode);
        
        if(listOfVCode.size() > 0){
            WrapperResponse = CARE_AutoUtilityController.PEVFortyFiveDaysCheck(listOfVCode);
            if(WrapperResponse.careAppPEVSet.size() > 0){
                for(Id recId : WrapperResponse.careAppPEVSet){
                    careAppPEVSet.add(recId); 
                }
            }
            if(WrapperResponse.careAppErrorIdSet.size() > 0){
                for(Id recId : WrapperResponse.careAppErrorIdSet){
                    careAppErrorIdSet.add(recId); 
                }
            }
            if(WrapperResponse.setErrorPerId.size() > 0){
                for(String perId : WrapperResponse.setErrorPerId){
                    setErrorPerId.add(perId); 
                }
            }
            
            
        }
        
        
    }
    
    /**
* Method name  : finish
* Description  : this method holds all the success records Ids which got inserted in CARE APP and CARE APP ENROLL SA
* Return Type  : void
* Parameter    : Database.BatchableContext 
**/
    global void finish(Database.BatchableContext BC) {
        
        string sEmail = '';
        
        // get email address for this job from CARE_System__c object.  If not value, use "mdsscareonesupport@pge.com"
        List<CARE_System_Value__c> systemValLst = [Select Name,SYSTEM_VALUE__c,SYSTEM_VALUE_TYPE__c from CARE_System_Value__c where Name ='Internal Support Email List' and SYSTEM_VALUE_TYPE__c = 'EMAIL' LIMIT 1];
        if(systemValLst.size() > 0 && systemValLst[0].SYSTEM_VALUE__c != null){
            sEmail = systemValLst[0].SYSTEM_VALUE__c;
        }
        else{
            sEmail = 'mdsscareonesupport@pge.com';
        }
        
        // get job status
        AsyncApexJob a = 
            [SELECT Id, CompletedDate, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email
             FROM AsyncApexJob WHERE Id = :BC.getJobId()];
        
        CARE_UtilityController.sendBatchCompletionEmail(sEmail, a.Status, a.CompletedDate, a.TotalJobItems, careAppPEVSet.size(), careAppErrorIdSet.size());
               
        system.debug('All fail Ids===' +careAppErrorIdSet);
        system.debug('All failed per Id===' +setErrorPerId);
        system.debug('All success Id---' +careAppPEVSet);
        system.debug('Total number of records processed' +recordsProcessed);
    }
}