force-app/main/default/objects/EI_SA_CONTERM__c/EI_SA_CONTERM__c.object-meta.xml
<CustomObject>
    <description>SA level rate contract riders for codes such as EMP-DSC.</description>
    <label>EI SA CONTERM</label>
    <nameField>
        <displayFormat>SACONT{0000000000}</displayFormat>
        <label>Sequence No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EI SA CONTERM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EI_SA_CONTERM__c/fields/BF_CD__c.field-meta.xml
<CustomField>
    <fullName>BF_CD__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>BF CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EI_SA_CONTERM__c/fields/END_DT__c.field-meta.xml
<CustomField>
    <fullName>END_DT__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>END DT</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EI_SA_CONTERM__c/fields/SERVICE_AGREEMENT__c.field-meta.xml
<CustomField>
    <fullName>SERVICE_AGREEMENT__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SERVICE AGREEMENT</label>
    <referenceTo>EI_Site__c</referenceTo>
    <relationshipLabel>EI SA CONTERM</relationshipLabel>
    <relationshipName>EI_SA_CONTERM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EI_Site__c/EI_Site__c.object-meta.xml
<CustomObject>
    <description>Sites are locations associated with Accounts, where work is performed.</description>
    <label>Site/Service Agreement</label>
    <nameField>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site/Service Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/EI_Site__c/fields/Person_ID_EI__c.field-meta.xml
<CustomField>
    <fullName>Person_ID_EI__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Person ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CARE_EmployeeDiscountController.cls
/***********************************************************************************************************   
Apex Util class Name :  CARE_EmployeeDiscountController
Version              :  1.0                                                                          
Created Date         :  06/01/2020                                                         
Function             :  This is the Apex class for Identifying Customer has employee Discount or Not 
Story                :                                                                               
Work Task            :                                                                               
Modification Log     :                                                                               
*----------------------------------------------------------------------------------------------------------  
* When                  Who                    						Description                                     
* ---------------------------------------------------------------------------------------------------------  
* 06/01/2020            CTS                  			 			Initial Version.
*                                             	 					CARE Application: 
****************************************************************************************************************************************/

public class CARE_EmployeeDiscountController {
    
    Private Static final Date dTodaysDate = Date.today();
    
    @InvocableMethod
    public static list<FlowOutputs> checkEmployeeDiscount(list<FlowInputs> listInputValues)
    {
        Boolean bEmpDiscount;
        String sPersId=listInputValues[0].sPersId;
        try{
            List <EI_SA_CONTERM__C> listEmpDiscount = [SELECT SA_ID__c, BF_CD__C, END_DT__C FROM EI_SA_CONTERM__C
                                                       WHERE SERVICE_AGREEMENT__r.Person_ID_EI__c = :sPersId AND BF_CD__C = :CARE_Constants.CARE_EMP_DISCOUNT_CODE
                                                       AND (END_DT__C >= :dTodaysDate OR END_DT__C = NULL)];
            if(listEmpDiscount.size()>0){
                bEmpDiscount = true;
            }
            else{
                bEmpDiscount = false;
            }
        }
        catch (Exception ex) {        
       EI_CreateErrorLog.upsertException(EI_CreateErrorLog.logException('CARE_EmployeeDiscountController',ex));
       CARE_UtilityController.sendExceptionEmail('CARE_EmployeeDiscountController', '','', sPersId, ex);
        } 
        
        FlowOutputs outPut=new FlowOutputs();
        outPut.bHasEmployeeDiscount=bEmpDiscount;
        List<FlowOutputs> listResults =new List<FlowOutputs>();  
        listResults.add(outPut); 
        return listResults;
    }
    
   //Wrapper class for Recieving input from flow 
    public class FlowInputs{
        @InvocableVariable
        public String sPersId;        
        
    }
    
    //Wrapper class for Recieving input from flow 
    public class FlowOutputs{
        @InvocableVariable
        public Boolean bHasEmployeeDiscount;        
        
    }
     
}