force-app/main/default/objects/CARE_Application__c/CARE_Application__c.object-meta.xml
<CustomObject>
    <label>CARE Application</label>
    <nameField>
        <displayFormat>CT-{0000000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE Application</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_Application__c/fields/ANNUAL_HOUSEHOLD_INCOME__c.field-meta.xml
<CustomField>
    <fullName>ANNUAL_HOUSEHOLD_INCOME__c</fullName>
    <label>ANNUAL HOUSEHOLD INCOME</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/APPLICANT_NAME__c.field-meta.xml
<CustomField>
    <fullName>APPLICANT_NAME__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>APPLICANT NAME</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/APPLICATION_STATUS__c.field-meta.xml
<CustomField>
    <fullName>APPLICATION_STATUS__c</fullName>
    <inlineHelpText>Status of Enrollment</inlineHelpText>
    <label>APPLICATION STATUS</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Decision Made</fullName>
            </value>
            <value>
                <fullName>Staged for CC&amp;B</fullName>
            </value>
            <value>
                <fullName>Sent to CC&amp;B</fullName>
            </value>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/BUREAU_INDIAN_AFFAIRS__c.field-meta.xml
<CustomField>
    <fullName>BUREAU_INDIAN_AFFAIRS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BUREAU INDIAN AFFAIRS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CALFRESH_SNAP__c.field-meta.xml
<CustomField>
    <fullName>CALFRESH_SNAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CALFRESH SNAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CALWORKS_TANF__c.field-meta.xml
<CustomField>
    <fullName>CALWORKS_TANF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CALWORKS TANF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CC_CL_CD__c.field-meta.xml
<CustomField>
    <fullName>CC_CL_CD__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DISCOUNT TYPE</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CCB_CONTACT_COMMENT__c.field-meta.xml
<CustomField>
    <fullName>CCB_CONTACT_COMMENT__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB CONTACT COMMENT</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/COC_CODE__c.field-meta.xml
<CustomField>
    <fullName>COC_CODE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>COC CODE</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/EMAIL_ADDRESS__c.field-meta.xml
<CustomField>
    <fullName>EMAIL_ADDRESS__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>EMAIL ADDRESS</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/ENROLLMENT_TYPE__c.field-meta.xml
<CustomField>
    <fullName>ENROLLMENT_TYPE__c</fullName>
    <label>ENROLLMENT TYPE</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ENROLLMENT</fullName>
            </value>
            <value>
                <fullName>PEV</fullName>
            </value>
            <value>
                <fullName>PEV Receipt</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/FIXED_INCOME__c.field-meta.xml
<CustomField>
    <fullName>FIXED_INCOME__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FIXED INCOME</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/FORM_CODE__c.field-meta.xml
<CustomField>
    <fullName>FORM_CODE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FORM CODE</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/HEAD_START_INCOME__c.field-meta.xml
<CustomField>
    <fullName>HEAD_START_INCOME__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HEAD START INCOME</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/HEALTHY_FAMILIES__c.field-meta.xml
<CustomField>
    <fullName>HEALTHY_FAMILIES__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HEALTHY FAMILIES</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/IS_RECERT__c.field-meta.xml
<CustomField>
    <fullName>IS_RECERT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IS RECERT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/IS_SIGNED__c.field-meta.xml
<CustomField>
    <fullName>IS_SIGNED__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IS SIGNED</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/LIHEAP__c.field-meta.xml
<CustomField>
    <fullName>LIHEAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LIHEAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/MEDICAID_OVER65__c.field-meta.xml
<CustomField>
    <fullName>MEDICAID_OVER65__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MEDICAID OVER65</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/MEDICAID_UNDER65__c.field-meta.xml
<CustomField>
    <fullName>MEDICAID_UNDER65__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MEDICAID UNDER65</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/NEED_NAME_CHANGE__c.field-meta.xml
<CustomField>
    <fullName>NEED_NAME_CHANGE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NEED NAME CHANGE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/NO_ADULT__c.field-meta.xml
<CustomField>
    <fullName>NO_ADULT__c</fullName>
    <label>NO ADULT</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/NO_CHILD__c.field-meta.xml
<CustomField>
    <fullName>NO_CHILD__c</fullName>
    <label>NO CHILD</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/NSLP__c.field-meta.xml
<CustomField>
    <fullName>NSLP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NSLP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/PROCESSED_DATE__c.field-meta.xml
<CustomField>
    <fullName>PROCESSED_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PROCESSED DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/RECEIVED_DATE__c.field-meta.xml
<CustomField>
    <fullName>RECEIVED_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RECEIVED DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/REQUEST_DROP__c.field-meta.xml
<CustomField>
    <fullName>REQUEST_DROP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>REQUEST DROP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/SOURCE_CHANNEL_TYPE__c.field-meta.xml
<CustomField>
    <fullName>SOURCE_CHANNEL_TYPE__c</fullName>
    <label>SOURCE CHANNEL TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Demand Status</fullName>
            </value>
            <value>
                <fullName>CARE Force.com</fullName>
            </value>
            <value>
                <fullName>CARE SMS</fullName>
            </value>
            <value>
                <fullName>CARE Flatsite</fullName>
            </value>
            <value>
                <fullName>CARE MyEnergy</fullName>
            </value>
            <value>
                <fullName>Regular App</fullName>
            </value>
            <value>
                <fullName>SoundBite</fullName>
            </value>
            <value>
                <fullName>Phone Enrollment</fullName>
            </value>
            <value>
                <fullName>Web Download</fullName>
            </value>
            <value>
                <fullName>Kiosk</fullName>
            </value>
            <value>
                <fullName>CASE/Adjustment</fullName>
            </value>
            <value>
                <fullName>CASE/Reinstatement</fullName>
            </value>
            <value>
                <fullName>CASE/Transfer</fullName>
            </value>
            <value>
                <fullName>CASE/Commodity</fullName>
            </value>
            <value>
                <fullName>PEV/Adjustment</fullName>
            </value>
            <value>
                <fullName>Enroll/Adjustment</fullName>
            </value>
            <value>
                <fullName>Bill Insert</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Allconnect</fullName>
            </value>
            <value>
                <fullName>ESA Enrollment</fullName>
            </value>
            <value>
                <fullName>DAC GT Enrollment</fullName>
            </value>
            <value>
                <fullName>Water Agency/IOU</fullName>
            </value>
            <value>
                <fullName>Batch</fullName>
            </value>
            <value>
                <fullName>DataXport Enrollment</fullName>
            </value>
            <value>
                <fullName>DataXport PEV Notice</fullName>
            </value>
            <value>
                <fullName>CARE New_Mover</fullName>
            </value>
            <value>
                <fullName>CARE IVR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/SSI__c.field-meta.xml
<CustomField>
    <fullName>SSI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SSI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/WIC__c.field-meta.xml
<CustomField>
    <fullName>WIC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WIC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EI_Site__c/EI_Site__c.object-meta.xml
<CustomObject>
    <description>Sites are locations associated with Accounts, where work is performed.</description>
    <label>Site/Service Agreement</label>
    <nameField>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site/Service Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/EI_Site__c/fields/EI_Premise__c.field-meta.xml
<CustomField>
    <fullName>EI_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The premise object that the site/SA is pointing to.</description>
    <inlineHelpText>The premise object that the site/SA is pointing to.</inlineHelpText>
    <label>Premise</label>
    <referenceTo>EI_PREMISE__c</referenceTo>
    <relationshipLabel>Site/Service Agreements</relationshipLabel>
    <relationshipName>Site_Service_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Care_VerifyEnrollmentBatchTest.cls
/***********************************************************************************************************   
Apex Util class Name :  Care_VerifyEnrollmentBatchTest
Version              :  1.0                                                                          
Created Date         :  07/28/2020                                                         
Function             :  This is the Test class for Calling Full Qualification Logic.
Story                :                                                                               
Work Task            :                                                                               
Modification Log     :                                                                               
*----------------------------------------------------------------------------------------------------------  
* When                  Who                                                 Description                                     
* ---------------------------------------------------------------------------------------------------------  
* 07/28/2020            Priyanka Nimkar                                     Initial Version.
****************************************************************************************************************************************/
@istest(SeeAllData=false)

public class Care_VerifyEnrollmentBatchTest {
    EI_Site__c lstSite = new EI_Site__c();
    
    @testSetup
    public static void makeData(){
        /*Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User lstusr = PM_EI_TestDataUtility.createUser(); //called testdatafactory for creation of user
        System.debug('lstusr is'+lstusr);
        lstusr.ProfileId = p.Id;
        insert lstusr;   // inserted user
        */
        List<Account> listAccountRecords = createAccountRecords();
        insert listAccountRecords;
        /*List<EI_PREMISE__c> listPremiseRecords = createPremiseRecords();
        insert listPremiseRecords;
        List<EI_Site__c> listSiteRecords = createSiteRecords(listAccountRecords);
        insert listSiteRecords;*/
        Case objCase = CARE_TestDataFactory.objCase();
        insert objCase;
        CARE_Application__c objCareApp = CARE_TestDataFactory.careApplication(listAccountRecords[0]);
        objCareApp.ENROLLMENT_TYPE__c = 'OTHER';
        objCareApp.CC_CL_CD__c = 'C';
        objCareApp.IS_RECERT__c =  true;
        objCareApp.NO_ADULT__c =  3;
        objCareApp.NO_CHILD__c =  1;
        objCareApp.IS_SIGNED__c =  true;
        objCareApp.REQUEST_DROP__c =  true;
        objCareApp.NEED_NAME_CHANGE__c =  false;
        objCareApp.APPLICANT_NAME__c =  'TestAman';
        objCareApp.RECEIVED_DATE__c =  date.today()-7;
        objCareApp.PROCESSED_DATE__c =  date.today()-5;
        objCareApp.SOURCE_CHANNEL_TYPE__c =  'DataXport Enrollment';
        objCareApp.FORM_CODE__c =  '';
        objCareApp.COC_CODE__c =  '';
        objCareApp.APPLICATION_STATUS__c = 'Pending';        
        objCareApp.LIHEAP__c =  false;
        objCareApp.WIC__c =  false;
        objCareApp.CALFRESH_SNAP__c =  false;
        objCareApp.CALWORKS_TANF__c =  false;
        objCareApp.HEAD_START_INCOME__c =  false;
        objCareApp.SSI__c =  true;
        objCareApp.HEALTHY_FAMILIES__c =  false;
        objCareApp.NSLP__c =  false;
        objCareApp.BUREAU_INDIAN_AFFAIRS__c =  true;
        objCareApp.MEDICAID_UNDER65__c =  true;
        objCareApp.MEDICAID_OVER65__c =  false;
        objCareApp.EMAIL_ADDRESS__c =  'abc@gmail.com';
        objCareApp.ANNUAL_HOUSEHOLD_INCOME__c =  1234;
        objCareApp.FIXED_INCOME__c =  false;
        objCareApp.ENROLLMENT_TYPE__c = 'ENROLLMENT'; 
        objCareApp.CCB_CONTACT_COMMENT__c = 'Not Proper';
        objCareApp.DROP_SOURCE__c = 'CC&B Case';
        objCareApp.REASON_DESC__c = 'Testing';
        insert objCareApp;
        //List<CARE_Type__c> lstCareTypes = createCareTypeRecords();
        //insert lstCareTypes;
        //
        // Create Email Address to which email should be sent with Batch Processing Statistics or Error details
        List<CARE_SYSTEM_VALUE__c> careSysList = CARE_TestDataFactory.createEmailAddrForBatchJobs();
        if (careSysList != null && !careSysList.isEmpty()) {
            insert careSysList;
        }
    }
    
    @isTest
    static void testMethod1(){
        makeData();
        Test.startTest();
        Database.executeBatch(new Care_VerifyEnrollmentBatch());
        Test.stopTest();
        
    }    
    
    private static List<Account> createAccountRecords(){
        List<Account> listAccountRecords = new List<Account>();
        
        Account objAccountRecord = PM_EI_TestDataUtility.createAccount();
        objAccountRecord.AccountNumber = '1224590384';
        objAccountRecord.CARE_DISCOUNT_TYPE__c = 'CARE';
        objAccountRecord.Encrypted_Account_Name__c = 'Test Dummy Acct';
        objAccountRecord.SAID__c = '7777777777';
        objAccountRecord.Phone = '9065231';
        objAccountRecord.Discount__c = 'C';
        objAccountRecord.Billing_Person_ID_EI__c = '0123456003';
        objAccountRecord.Service_Address__c = 'Search1234';
        objAccountRecord.SA_Type__c = 'E';
        objAccountRecord.Encrypted_Account_Name__c = 'Encrypted';
        objAccountRecord.Type = 'Type';
        objAccountRecord.Rate__c = 'HAG1A';
        objAccountRecord.Branch_Code_EI__c = 'Get';
        objAccountRecord.Original_Tree_Level_EI__c = 2.0;
        listAccountRecords.add(objAccountRecord);  
        
        return listAccountRecords;
    }
    private static List<EI_Site__c> createSiteRecords(List<Account> listAccountRecords){
        List<EI_Site__c> listSiteRecords = new List<EI_Site__c>();
        
        //Site record with status as '20', with valid Rate Schedule, and discount in 'Electric'
        EI_Site__c objSite1 = CARE_TestDataFactory.createSite(listAccountRecords);
        objSite1.Name='Site1';
        objSite1.Rate_Schedule_EI__c='STANDARD';
        objSite1.Imported_Site_Name_EI__c = 'MEDRANO,JOSE';
        objSite1.Site_Premise_ID_EI__c = 'Prem3';
        objSite1.Care_Start_Date_EI__c = date.today();
        objSite1.Care_Stop_Date_EI__c = date.today()+30;
        objSite1.Svc_Status_Code_EI__c = '20';
        objSite1.Svc_Type_Code_EI__c = 'E';
        listSiteRecords.add(objSite1);
        
        //Site record with status as '30', with invalid Rate Schedule, and discount in 'Gas'
        EI_Site__c objSite2 = CARE_TestDataFactory.createSite(listAccountRecords);
        objSite2.Name='Site2';
        objSite2.Rate_Schedule_EI__c='EVA';
        objSite2.Imported_Site_Name_EI__c = 'MEDRANO,JOSE';
        objSite2.Site_Premise_ID_EI__c = 'Prem4';
        objSite2.Care_Start_Date_EI__c = date.today();
        objSite2.Care_Stop_Date_EI__c = date.today()+60;
        objSite2.Svc_Status_Code_EI__c = '30';
        objSite2.Svc_Type_Code_EI__c = 'G';
        listSiteRecords.add(objSite2);    
        
        //Site record with status as '10', and Care_Stop_Date_EI__c <todays date, so that it is not in any discount for 'Gas'
/*        EI_Site__c objSite3 = CARE_TestDataFactory.createSite(listAccountRecords);
        objSite3.Name='Site3';
        objSite3.Rate_Schedule_EI__c='STANDARD';
        objSite3.Imported_Site_Name_EI__c = 'MEDRANO,JOSE';
        objSite3.Site_Premise_ID_EI__c = 'Prem1';
        objSite3.Care_Start_Date_EI__c = date.today()-10;
        objSite3.Care_Stop_Date_EI__c = date.today()-5;
        objSite3.Svc_Status_Code_EI__c = '10';
        objSite3.Svc_Type_Code_EI__c = 'G';
        listSiteRecords.add(objSite3);    
        
        //Create record with Invalid status, invalid Rate schedule, Care Stop Date < todays date (for method getAddElecGasForCustomerNoValidDiscountDiscTest)
        EI_Site__c objSite4 = CARE_TestDataFactory.createSite(listAccountRecords);
        objSite4.Name='Site4';
        objSite4.Rate_Schedule_EI__c='EVA';
        objSite4.Billing_Account_ID_EI__c = '6767676767';
        objSite4.Imported_Site_Name_EI__c = 'PABLO,JORGE';
        objSite4.Person_ID_EI__c = '9000000001';
        objSite4.Site_Premise_ID_EI__c = 'Prem3';
        objSite4.Care_Start_Date_EI__c = date.today()-10;
        objSite4.Care_Stop_Date_EI__c = date.today()-5;
        objSite4.SAID_EI__c = '6456456456';
        objSite4.Svc_Status_Code_EI__c = '30';
        listSiteRecords.add(objSite4);
 */       
        return listSiteRecords;
    }
    private static List<EI_PREMISE__c> createPremiseRecords(){
        List<EI_PREMISE__c> listPremiseRecords = new List<EI_PREMISE__c>();
        
        EI_PREMISE__c prmemiseRecord1 = CARE_TestDataFactory.createPremise('Prem3', '3333333333');
        listPremiseRecords.add(prmemiseRecord1);
        
        //EI_PREMISE__c prmemiseRecord2 = CARE_TestDataFactory.createPremise('Prem4', '4444444444');
        //listPremiseRecords.add(prmemiseRecord2);
        
        return listPremiseRecords;    
    }
}