force-app/main/default/objects/CARE_Application__c/CARE_Application__c.object-meta.xml
<CustomObject>
    <label>CARE Application</label>
    <nameField>
        <displayFormat>CT-{0000000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE Application</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_Application__c/fields/ACCT_ID__c.field-meta.xml
<CustomField>
    <fullName>ACCT_ID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>ACCT ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/APPLICANT_NAME__c.field-meta.xml
<CustomField>
    <fullName>APPLICANT_NAME__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>APPLICANT NAME</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/APPLICATION_EXTERNAL_ID__c.field-meta.xml
<CustomField>
    <fullName>APPLICATION_EXTERNAL_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>APPLICATION EXTERNAL ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/APPLICATION_STATUS__c.field-meta.xml
<CustomField>
    <fullName>APPLICATION_STATUS__c</fullName>
    <inlineHelpText>Status of Enrollment</inlineHelpText>
    <label>APPLICATION STATUS</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Decision Made</fullName>
            </value>
            <value>
                <fullName>Staged for CC&amp;B</fullName>
            </value>
            <value>
                <fullName>Sent to CC&amp;B</fullName>
            </value>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/APPLICATION_TYPE__c.field-meta.xml
<CustomField>
    <fullName>APPLICATION_TYPE__c</fullName>
    <label>APPLICATION TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrollment</fullName>
            </value>
            <value>
                <fullName>PEV</fullName>
            </value>
            <value>
                <fullName>Notice</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CARE_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>CARE_Account_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account number of customer enrolled</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CARE Application</relationshipLabel>
    <relationshipName>CARE_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CCB_CONTACT_CODE__c.field-meta.xml
<CustomField>
    <fullName>CCB_CONTACT_CODE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB CONTACT CODE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CCB_CONTACT_COMMENT__c.field-meta.xml
<CustomField>
    <fullName>CCB_CONTACT_COMMENT__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB CONTACT COMMENT</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CCB_CONTACT_DESC__c.field-meta.xml
<CustomField>
    <fullName>CCB_CONTACT_DESC__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB CONTACT DESC</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CCB_Contact_Type_No__c.field-meta.xml
<CustomField>
    <fullName>CCB_Contact_Type_No__c</fullName>
    <description>The care type no for the contact code selected</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB Contact Type No</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/ENROLLMENT_TYPE__c.field-meta.xml
<CustomField>
    <fullName>ENROLLMENT_TYPE__c</fullName>
    <label>ENROLLMENT TYPE</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ENROLLMENT</fullName>
            </value>
            <value>
                <fullName>PEV</fullName>
            </value>
            <value>
                <fullName>PEV Receipt</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/PER_ID__c.field-meta.xml
<CustomField>
    <fullName>PER_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PER ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/PROCESSED_DATE__c.field-meta.xml
<CustomField>
    <fullName>PROCESSED_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PROCESSED DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/RECEIVED_DATE__c.field-meta.xml
<CustomField>
    <fullName>RECEIVED_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RECEIVED DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/RESULT_DATE__c.field-meta.xml
<CustomField>
    <fullName>RESULT_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RESULT DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/SOURCE_CHANNEL_TYPE__c.field-meta.xml
<CustomField>
    <fullName>SOURCE_CHANNEL_TYPE__c</fullName>
    <label>SOURCE CHANNEL TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Demand Status</fullName>
            </value>
            <value>
                <fullName>CARE Force.com</fullName>
            </value>
            <value>
                <fullName>CARE SMS</fullName>
            </value>
            <value>
                <fullName>CARE Flatsite</fullName>
            </value>
            <value>
                <fullName>CARE MyEnergy</fullName>
            </value>
            <value>
                <fullName>Regular App</fullName>
            </value>
            <value>
                <fullName>SoundBite</fullName>
            </value>
            <value>
                <fullName>Phone Enrollment</fullName>
            </value>
            <value>
                <fullName>Web Download</fullName>
            </value>
            <value>
                <fullName>Kiosk</fullName>
            </value>
            <value>
                <fullName>CASE/Adjustment</fullName>
            </value>
            <value>
                <fullName>CASE/Reinstatement</fullName>
            </value>
            <value>
                <fullName>CASE/Transfer</fullName>
            </value>
            <value>
                <fullName>CASE/Commodity</fullName>
            </value>
            <value>
                <fullName>PEV/Adjustment</fullName>
            </value>
            <value>
                <fullName>Enroll/Adjustment</fullName>
            </value>
            <value>
                <fullName>Bill Insert</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Allconnect</fullName>
            </value>
            <value>
                <fullName>ESA Enrollment</fullName>
            </value>
            <value>
                <fullName>DAC GT Enrollment</fullName>
            </value>
            <value>
                <fullName>Water Agency/IOU</fullName>
            </value>
            <value>
                <fullName>Batch</fullName>
            </value>
            <value>
                <fullName>DataXport Enrollment</fullName>
            </value>
            <value>
                <fullName>DataXport PEV Notice</fullName>
            </value>
            <value>
                <fullName>CARE New_Mover</fullName>
            </value>
            <value>
                <fullName>CARE IVR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Type__c/CARE_Type__c.object-meta.xml
<CustomObject>
    <label>Reason/Contact Maintenance</label>
    <nameField>
        <displayFormat>CTNO-{000000}</displayFormat>
        <label>Seq No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reason/Contact Maintenance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_Type__c/fields/TYPE_CODE__c.field-meta.xml
<CustomField>
    <fullName>TYPE_CODE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TYPE CODE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Type__c/fields/TYPE_DESC__c.field-meta.xml
<CustomField>
    <fullName>TYPE_DESC__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>REASON(TYPE DESC)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CARE_Type__c/fields/TYPE_DESC_LONG__c.field-meta.xml
<CustomField>
    <fullName>TYPE_DESC_LONG__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TYPE DESC LONG</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EI_Site__c/EI_Site__c.object-meta.xml
<CustomObject>
    <description>Sites are locations associated with Accounts, where work is performed.</description>
    <label>Site/Service Agreement</label>
    <nameField>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site/Service Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/CARE_SendAppController.cls
/***********************************************************************************************************   
Apex Util class Name :  CARE_SendAppController
Version              :  1.0                                                                          
Created Date         :  06/05/2020                                                         
Function             :  This is the Apex COntroller for Send App of CARE Application Component.
Story                :                                                                               
Work Task            :                                                                               
Modification Log     :                                                                               
*----------------------------------------------------------------------------------------------------------  
* When                  Who                    Description                                     
* ---------------------------------------------------------------------------------------------------------  
* 06/06/2020            SKMN                   Initial Version.
*                                              CARE Application: 
* 08/28/2020			SKMN				   Updated to stamp extra fields for all applications
****************************************************************************************************************************************/
public class CARE_SendAppController {
    
    /******************************************WRAPPER CLASSES*************************************** */
    //Custom Wrapper class for User List
    public class SendAppWrapper
    {
        @AuraEnabled public Boolean bSuccess{get;set;}
        @AuraEnabled public String sErrorCode{get;set;}
        @AuraEnabled public String sErrorMessage{get;set;}
        @AuraEnabled public String sComment{get;set;}
        @AuraEnabled public String sContactCode{get;set;}
        public SendAppWrapper()
        {
            bSuccess = true;
            sErrorCode = '';
            sErrorMessage = '';
            sComment = '';
            sContactCode = '';
        }        
    } 
    public class SendAppWrapperReq
    {
        @AuraEnabled public String sPerId{get;set;}
        @AuraEnabled public String sAccId{get;set;}
        @AuraEnabled public String sBillingAccId{get;set;}
        @AuraEnabled public String sApplicantName{get;set;}         
    }   
    
    /******************************************WRAPPER CLASSES*************************************** */
    
    /******************************************PUBLIC METHODS*************************************** */
    
    @AuraEnabled
    public static SendAppWrapper getSendAppDetails(String sPersonId){
        List<CARE_Type__c> listCareType = new List<CARE_Type__c>();
        SendAppWrapper sendAppWrapper = new SendAppWrapper();
        try{
            //get the cc code details for Send App
            listCareType = CARE_UtilityController.getCCCode(CARE_Constants.CARE_CC_SEND_APP, null, null);   
            sendAppWrapper.sComment = listCareType[0].TYPE_DESC_LONG__c;
            sendAppWrapper.sContactCode = listCareType[0].TYPE_CODE__c;
            sendAppWrapper.bSuccess = true;
        }
        catch(Exception ex){
            sendAppWrapper.bSuccess = false;
            sendAppWrapper.sErrorCode = CARE_Constants.CARE_APPLICATION_ERROR;
            sendAppWrapper.sErrorMessage = ex.getMessage();
            
            EI_CreateErrorLog.upsertException(EI_CreateErrorLog.logException(CARE_Constants.CLASS_NAME_CARE_SEND_APP_CONTROLLER, ex));
            CARE_UtilityController.sendExceptionEmail(CARE_Constants.CLASS_NAME_CARE_SEND_APP_CONTROLLER, '', '', sPersonId, ex);
        }
        
        return sendAppWrapper;
    }
    
    //This method is used to save record in Care_Application__c object for sending application via CC&B, for those customer who does not have a CARE/FERA enrollment
    @AuraEnabled
    public static SendAppWrapper createTransactionForSendApp(SendAppWrapperReq objSendApp){
        Date dTodaysDate = Date.today();
        Map <String, EI_SITE__C> mapValidSAForPerId = new Map <String, EI_SITE__C>();
        SendAppWrapper sendAppWrapper = new SendAppWrapper();
        
        try{
            Id userId = UserInfo.getUserId();            
            User userDetails = [SELECT Profile.Name, LAN_ID_EI__c FROM User WHERE ID = :userId];
            
            Id careAppRecTypeId = CARE_UtilityController.getObjectRecordTypeId(CARE_Constants.RES_CUST_DEVELOPER_NAME);
            
            //Get the CC Code for 'A' for stamping
            List<CARE_Type__c> listCareType = CARE_UtilityController.getCCCode(CARE_Constants.CARE_CC_SEND_APP, null, null);
            
            //Create record in CARE_Application__c
            CARE_Application__c careApp = new CARE_Application__c();   
            careApp.RecordTypeId = careAppRecTypeId;
            careApp.APPLICANT_NAME__c = objSendApp.sApplicantName;
            careApp.APPLICATION_STATUS__c = CARE_Constants.CARE_DECISION_MADE;            
            careApp.PROCESSED_DATE__c = dTodaysDate;
            careApp.PER_ID__c = objSendApp.sPerId;
            careApp.CARE_Account_ID__c = objSendApp.sAccId;
            careApp.ACCT_ID__c = objSendApp.sBillingAccId;
            careApp.CCB_Contact_Type_No__c = CARE_Constants.CARE_CC_SEND_APP;
            careApp.CCB_CONTACT_CODE__c = listCareType[0].TYPE_CODE__c;
            careApp.CCB_CONTACT_DESC__c= listCareType[0].TYPE_DESC__c;
            careApp.CCB_CONTACT_COMMENT__c = listCareType[0].TYPE_DESC_LONG__c.replace(CARE_Constants.CARE_LAN_ID_PLACEHOLDER, (userDetails.LAN_ID_EI__c != null) ? userDetails.LAN_ID_EI__c : '');
            careApp.ENROLLMENT_TYPE__c = 'OTHER'; //ENROLLMENT, PEV, PEV NOTICE, OTHER
            //careApp.ENROLLMENT_TYPE__c = null;
            //careApp.APPLICATION_EXTERNAL_ID__c = 'EN'; //EN or PE or BA
            //careApp.APPLICATION_TYPE__c = 'Enrollment';     //Enrollment,PEV,Notice,Other  
            careApp.SOURCE_CHANNEL_TYPE__c = CARE_Constants.CARE_CHANNEL_TYPE_REGULAR_APP;
            careApp.RECEIVED_DATE__c = dTodaysDate;//Extra fields    
            careApp.USER_NAME_CARE1__c = (userDetails.LAN_ID_EI__c != null) ? userDetails.LAN_ID_EI__c : '';//Extra fields
            careApp.RESULT_DATE__c = dTodaysDate;//Extra fields
            
            insert careApp; 
            
            sendAppWrapper.bSuccess = true;
        }
        catch (Exception ex) {
            sendAppWrapper.bSuccess = false;
            sendAppWrapper.sErrorCode = CARE_Constants.CARE_APPLICATION_ERROR;
            sendAppWrapper.sErrorMessage = ex.getMessage();
            
            EI_CreateErrorLog.upsertException(EI_CreateErrorLog.logException(CARE_Constants.CLASS_NAME_CARE_SEND_APP_CONTROLLER, ex));
            CARE_UtilityController.sendExceptionEmail(CARE_Constants.CLASS_NAME_CARE_SEND_APP_CONTROLLER, '', '', objSendApp.sPerId, ex);            
        }  
        return sendAppWrapper;
    }
    
    /******************************************PUBLIC METHODS*************************************** */
    
}