force-app/main/default/objects/Account/fields/CARE_DISCOUNT_TYPE__c.field-meta.xml
<CustomField>
    <fullName>CARE_DISCOUNT_TYPE__c</fullName>
    <label>CARE DISCOUNT TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CARE</fullName>
            </value>
            <value>
                <fullName>FERA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Application__c/CARE_Application__c.object-meta.xml
<CustomObject>
    <label>CARE Application</label>
    <nameField>
        <displayFormat>CT-{0000000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE Application</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_Application__c/fields/ACCT_ID__c.field-meta.xml
<CustomField>
    <fullName>ACCT_ID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>ACCT ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/APPLICANT_NAME__c.field-meta.xml
<CustomField>
    <fullName>APPLICANT_NAME__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>APPLICANT NAME</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/APPLICATION_EXTERNAL_ID__c.field-meta.xml
<CustomField>
    <fullName>APPLICATION_EXTERNAL_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>APPLICATION EXTERNAL ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/APPLICATION_STATUS__c.field-meta.xml
<CustomField>
    <fullName>APPLICATION_STATUS__c</fullName>
    <inlineHelpText>Status of Enrollment</inlineHelpText>
    <label>APPLICATION STATUS</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Decision Made</fullName>
            </value>
            <value>
                <fullName>Staged for CC&amp;B</fullName>
            </value>
            <value>
                <fullName>Sent to CC&amp;B</fullName>
            </value>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/APPLICATION_TYPE__c.field-meta.xml
<CustomField>
    <fullName>APPLICATION_TYPE__c</fullName>
    <label>APPLICATION TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrollment</fullName>
            </value>
            <value>
                <fullName>PEV</fullName>
            </value>
            <value>
                <fullName>Notice</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CARE_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>CARE_Account_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account number of customer enrolled</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CARE Application</relationshipLabel>
    <relationshipName>CARE_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CARE_CI_CC__c.field-meta.xml
<CustomField>
    <fullName>CARE_CI_CC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CARE CI CC</label>
    <referenceTo>CARE_CI_CC__c</referenceTo>
    <relationshipLabel>CARE Application</relationshipLabel>
    <relationshipName>CARE_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CC_CL_CD__c.field-meta.xml
<CustomField>
    <fullName>CC_CL_CD__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DISCOUNT TYPE</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CCB_CONTACT_CODE__c.field-meta.xml
<CustomField>
    <fullName>CCB_CONTACT_CODE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB CONTACT CODE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CCB_CONTACT_COMMENT__c.field-meta.xml
<CustomField>
    <fullName>CCB_CONTACT_COMMENT__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB CONTACT COMMENT</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CCB_CONTACT_DESC__c.field-meta.xml
<CustomField>
    <fullName>CCB_CONTACT_DESC__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB CONTACT DESC</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CCB_Contact_Type_No__c.field-meta.xml
<CustomField>
    <fullName>CCB_Contact_Type_No__c</fullName>
    <description>The care type no for the contact code selected</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB Contact Type No</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/ENROLLMENT_TYPE__c.field-meta.xml
<CustomField>
    <fullName>ENROLLMENT_TYPE__c</fullName>
    <label>ENROLLMENT TYPE</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ENROLLMENT</fullName>
            </value>
            <value>
                <fullName>PEV</fullName>
            </value>
            <value>
                <fullName>PEV Receipt</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/PER_ID__c.field-meta.xml
<CustomField>
    <fullName>PER_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PER ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/PROCESSED_DATE__c.field-meta.xml
<CustomField>
    <fullName>PROCESSED_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PROCESSED DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/RECEIVED_DATE__c.field-meta.xml
<CustomField>
    <fullName>RECEIVED_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RECEIVED DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/CARE_CC_Batch_Detail__c.object-meta.xml
<CustomObject>
    <description>CARE CC Batch Detail</description>
    <label>CARE CC Batch Detail</label>
    <nameField>
        <displayFormat>CCD{0000000000}</displayFormat>
        <label>Name(Sequence No)</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE CC Batch Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/APPLICATION__c.field-meta.xml
<CustomField>
    <fullName>APPLICATION__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>APPLICATION</label>
    <referenceTo>CARE_Application__c</referenceTo>
    <relationshipLabel>CARE CC Batch Detail</relationshipLabel>
    <relationshipName>CARE_CC_Batch_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/CARE_CI_CC__c.field-meta.xml
<CustomField>
    <fullName>CARE_CI_CC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CARE CI CC</label>
    <referenceTo>CARE_CI_CC__c</referenceTo>
    <relationshipLabel>CARE CC Batch Detail</relationshipLabel>
    <relationshipName>CARE_CC_Batch_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/CC_CL_CD__c.field-meta.xml
<CustomField>
    <fullName>CC_CL_CD__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CC CL CD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/CC_TYPE_CD__c.field-meta.xml
<CustomField>
    <fullName>CC_TYPE_CD__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CC TYPE CD</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_CC_Batch_Detail__c/fields/CCB_Contact_Type_No__c.field-meta.xml
<CustomField>
    <fullName>CCB_Contact_Type_No__c</fullName>
    <description>Use the value in CARE_application</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB Contact Type No</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_CI_CC__c/CARE_CI_CC__c.object-meta.xml
<CustomObject>
    <description>CARE CI CC data from CC&amp;B</description>
    <label>CARE CI CC</label>
    <nameField>
        <displayFormat>CICC{0000000000}</displayFormat>
        <label>Sequence No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE CI CC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_CI_CC__c/fields/CC_DTTM__c.field-meta.xml
<CustomField>
    <fullName>CC_DTTM__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CC DTTM</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_CI_CC__c/fields/PER_ID__c.field-meta.xml
<CustomField>
    <fullName>PER_ID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>PER ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_System_Value__c/CARE_System_Value__c.object-meta.xml
<CustomObject>
    <description>Object to store system configuration values</description>
    <label>CARE System Value</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>NAME</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CARE System Value</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_System_Value__c/fields/SYSTEM_VALUE__c.field-meta.xml
<CustomField>
    <fullName>SYSTEM_VALUE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SYSTEM VALUE</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CARE_System_Value__c/fields/SYSTEM_VALUE_CODE__c.field-meta.xml
<CustomField>
    <fullName>SYSTEM_VALUE_CODE__c</fullName>
    <externalId>true</externalId>
    <label>SYSTEM VALUE CODE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CARE_Type__c/CARE_Type__c.object-meta.xml
<CustomObject>
    <label>Reason/Contact Maintenance</label>
    <nameField>
        <displayFormat>CTNO-{000000}</displayFormat>
        <label>Seq No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reason/Contact Maintenance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_Type__c/fields/TYPE_CODE__c.field-meta.xml
<CustomField>
    <fullName>TYPE_CODE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TYPE CODE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Type__c/fields/TYPE_DESC__c.field-meta.xml
<CustomField>
    <fullName>TYPE_DESC__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>REASON(TYPE DESC)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CARE_Type__c/fields/TYPE_DESC_LONG__c.field-meta.xml
<CustomField>
    <fullName>TYPE_DESC_LONG__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TYPE DESC LONG</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CARE_Type__c/fields/TYPE_NO__c.field-meta.xml
<CustomField>
    <fullName>TYPE_NO__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>TYPE NO</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/EI_Site__c/EI_Site__c.object-meta.xml
<CustomObject>
    <description>Sites are locations associated with Accounts, where work is performed.</description>
    <label>Site/Service Agreement</label>
    <nameField>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site/Service Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/EI_Site__c/fields/Account_EI__c.field-meta.xml
<CustomField>
    <fullName>Account_EI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site/Service Agreements (Account)</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EI_Site__c/fields/CARE_DISCOUNT_TYPE__c.field-meta.xml
<CustomField>
    <fullName>CARE_DISCOUNT_TYPE__c</fullName>
    <label>CARE DISCOUNT TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CARE</fullName>
            </value>
            <value>
                <fullName>FERA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CARE_OnDemandPEVController.cls
/***********************************************************************************************************   
Apex Util class Name :  CARE_OnDemandPEVController
Version              :  1.0                                                                          
Created Date         :  07/03/2020                                                         
Function             :  This is the Apex COntroller for sending On Demand PEV  request for customer.
Story                :                                                                               
Work Task            :                                                                               
Modification Log     :                                                                               
*----------------------------------------------------------------------------------------------------------  
* When                  Who                    Description                                     
* ---------------------------------------------------------------------------------------------------------  
* 07/03/2020            CTS                   Initial Version.
*                                             CARE Application: 
* 08/28/2020			SKMN				  Updated to stamp extra fields for all applications
**************************************************************************************************************/
public with sharing class CARE_OnDemandPEVController {
    
    /******************************************WRAPPER CLASSES*************************************** */
    //Custom Wrapper class for User List
    public class OnDemandPEVWrapper{
        @AuraEnabled public Boolean bSuccess{get;set;}
        @AuraEnabled public String sErrorCode{get;set;}
        @AuraEnabled public String sErrorMessage{get;set;}
        //@AuraEnabled public String sComment{get;set;}
        //@AuraEnabled public String sContactCode{get;set;}
        public OnDemandPEVWrapper()
        {
            bSuccess = true;
            sErrorCode = '';
            sErrorMessage = '';
            //sComment = '';
            //sContactCode = '';
        }        
    } 
    
    public class OnDemandPEVWrapperReq{
        @AuraEnabled public String sPerId{get;set;}
        @AuraEnabled public String sAccId{get;set;}
        @AuraEnabled public String sBillingAccId{get;set;}
        @AuraEnabled public String sApplicantName{get;set;}         
    }   
    
    /******************************************WRAPPER CLASSES*************************************** */
    
    
    /******************************************PUBLIC METHODS*************************************** */
    @AuraEnabled
    public static OnDemandPEVWrapper getCustomerDetails(string sPersonId){
        
		//string sPerId = '4155837704';
		OnDemandPEVWrapper OnDemandPEVWrapper = new OnDemandPEVWrapper();
        //List<CARE_Application__c> listPEVHU = new List<CARE_Application__c>();
        
        //String sSystemValue = [Select SYSTEM_VALUE__c from CARE_System_Value__c where SYSTEM_VALUE_CODE__c = 810 limit 1].SYSTEM_VALUE__c;
		//Integer i = Integer.valueOf(sSystemValue);
        Integer iSystemValue;
        Date dTodaysDate = Date.today();
		Date dDateBeforeFortyFiveDays;
        Map <String, EI_SITE__C> mapValidSAForPerId = new Map <String, EI_SITE__C>();
        List<CARE_System_Value__c> listGetSystemValue = new List<CARE_System_Value__c>();
        List<Integer> listCareSystemValue = new List<Integer>{CARE_Constants.CARE_PEV_SystemValueCode};
        //String sCustomerOnDiscount;
        system.debug('listCareSystemValue-->'+listCareSystemValue);
        try{
            if(listCareSystemValue.size() > 0){
            listGetSystemValue = CARE_UtilityController.getCareSystemValue(listCareSystemValue);
            system.debug('listGetSystemValue--->'+listGetSystemValue);
            }
            
            if(listGetSystemValue.size() > 0){
                for(CARE_System_Value__c careSystemRecord : listGetSystemValue){
                    if(careSystemRecord.SYSTEM_VALUE_CODE__c == CARE_Constants.CARE_PEV_SystemValueCode){
                        iSystemValue = Integer.valueOf(careSystemRecord.SYSTEM_VALUE__c);
                        system.debug('iSystemValue--->'+iSystemValue);
                    }
                } 
            }else{
                iSystemValue = CARE_Constants.CARE_FortyFiveDay;
            }
            dDateBeforeFortyFiveDays = dTodaysDate.addDays(-iSystemValue);
            
        mapValidSAForPerId = CARE_UtilityController.getActiveSADetailsForPersonId(sPersonId);
        List<CARE_CC_Batch_Detail__c> listCareCCBatchForCust = [select Id, CARE_CI_CC__r.CC_DTTM__c, CARE_CI_CC__r.CC_TYPE_CD__c from CARE_CC_Batch_Detail__c
                                              					where PER_ID__c =: sPersonId];
        
        
        /*List<CARE_Application__c> listCareCust = [select Id, CCB_CONTACT_CODE__c, CreatedDate from CARE_Application__c
                                              where PER_ID__c =: sPersonId];*/ 
        
        system.debug('mapValidSAForPerId size--->'+ mapValidSAForPerId.size());
        system.debug('listCareCCBatchForCust size--->'+ listCareCCBatchForCust.size());
        
        /*if(listCareCust.size() > 0){
            for(CARE_Application__c careApp : listCareCust){
                if(careApp.CCB_CONTACT_CODE__c == 'V' || careApp.CCB_CONTACT_CODE__c == 'VH')
                listPEVHU.add(careApp);
                //break;
            }
        }*/
        
            if(mapValidSAForPerId.size() > 0){
          //if(listCareCust.size() > 0){
            for(CARE_CC_Batch_Detail__c carePEV : listCareCCBatchForCust){
                if((carePEV.CARE_CI_CC__r.CC_TYPE_CD__c == CARE_Constants.CARE_CC_PEV || carePEV.CARE_CI_CC__r.CC_TYPE_CD__c == CARE_Constants.CARE_CC_HU) && carePEV.CARE_CI_CC__r.CC_DTTM__c >= dDateBeforeFortyFiveDays){
                  OnDemandPEVWrapper.bSuccess = true;
                  break;  
                }else{
                   OnDemandPEVWrapper.bSuccess = false;
                   OnDemandPEVWrapper.sErrorCode = CARE_Constants.CARE_ONDEMANDPEV_ERROR;
                }
            }
        }
        //else if(mapValidSAForPerId.size() <= 0 && listCareCCBatchForCust.size() <= 0){
         else if(mapValidSAForPerId.size() <= 0){
            	OnDemandPEVWrapper.bSuccess = true;
            	//OnDemandPEVWrapper.sErrorCode = CARE_Constants.CARE_ONDEMANDPEV_ERROR;
        }else{
                OnDemandPEVWrapper.bSuccess = false;
                OnDemandPEVWrapper.sErrorCode = CARE_Constants.CARE_ONDEMANDPEV_ERROR;
        }
   }catch(Exception ex){
            //OnDemandPEVWrapper.bSuccess = false;
            //OnDemandPEVWrapper.sErrorCode = CARE_Constants.CARE_ONDEMANDPEV_ERROR;
            //OnDemandPEVWrapper.sErrorMessage = ex.getMessage();
            EI_CreateErrorLog.upsertException(EI_CreateErrorLog.logException('CARE_OnDemandPEVController',ex));
            CARE_UtilityController.sendExceptionEmail('CARE_OnDemandPEVController','','',sPersonId, ex);
   }
        
        
		system.debug('OnDemandPEVWrapper.bSuccess--->'+ OnDemandPEVWrapper.bSuccess);        
        return OnDemandPEVWrapper;
        
    }
    
    @AuraEnabled
    public static OnDemandPEVWrapper createTransactionForOnDemandPEV(OnDemandPEVWrapperReq objOnDemandPEV){
        
        system.debug('inside createTransactionForOnDemandPEV method----->');
        
        List<CARE_Type__c> listCareTypeVE = CARE_UtilityController.getCCCode(CARE_Constants.CARE_CC_PEVOnDemand, null,null);
        List<CARE_Type__c> listCareTypeVHE = CARE_UtilityController.getCCCode(CARE_Constants.CARE_CC_PEVHighUsageOnDemand, null,null);
        
        Date dTodaysDate = Date.today();
        Date dDateBeforeTwoYears = dTodaysDate.addYears(-2);
        string sCCContactCode = listCareTypeVE[0].TYPE_CODE__c; //'VE';
        OnDemandPEVWrapper OnDemandPEVWrapper = new OnDemandPEVWrapper();
        OnDemandPEVWrapper.bSuccess = false;
        List<CARE_Application__c> listCareApp = new List<CARE_Application__c>();
        
        /*List<CARE_Application__c> listCCCodeAssign = [select Id, CCB_CONTACT_CODE__c, CreatedDate from CARE_Application__c
                                                     where PER_ID__c =: objOnDemandPEV.sPerId];*/
        
        try{
        List<CARE_CC_Batch_Detail__c> listCCCodeAssign = [select Id, CARE_CI_CC__r.CC_DTTM__c, CARE_CI_CC__r.CC_TYPE_CD__c, CC_CL_CD__c, APPLICATION__r.CARE_Account_ID__r.CARE_DISCOUNT_TYPE__c
                                                          from CARE_CC_Batch_Detail__c where PER_ID__c =: objOnDemandPEV.sPerId];
            
         List<EI_Site__c> listAcctDiscountType = [select Id, Account_EI__r.CARE_DISCOUNT_TYPE__c
                                                  from EI_Site__c where Account_EI__c =: objOnDemandPEV.sAccId];   
               
        if(listCCCodeAssign.size() > 0){
            for(CARE_CC_Batch_Detail__c objCare : listCCCodeAssign){
                if(objCare.CARE_CI_CC__r.CC_TYPE_CD__c == CARE_Constants.CARE_CC_HU && objCare.CARE_CI_CC__r.CC_DTTM__c >= dDateBeforeTwoYears){
                  sCCContactCode = listCareTypeVHE[0].TYPE_CODE__c; //'VHE';
                    break;
                }
            }
        }
            system.debug('sCCContactCode value----->'+ sCCContactCode);
            
            //Fetch the user's LANID to stamp as CommittedBy
            Id userId = UserInfo.getUserId();            
            User userDetails = [SELECT Profile.Name, LAN_ID_EI__c FROM User WHERE ID = :userId];
            
            Id careAppRecTypeId = CARE_UtilityController.getObjectRecordTypeId(CARE_Constants.RES_CUST_DEVELOPER_NAME); 
            
            //Create record in CARE_Application__c
            CARE_Application__c careApp = new CARE_Application__c();   
            careApp.RecordTypeId = careAppRecTypeId;
            careApp.APPLICANT_NAME__c = objOnDemandPEV.sApplicantName;
            careApp.APPLICATION_STATUS__c = CARE_Constants.CARE_DECISION_MADE;
            careApp.RECEIVED_DATE__c = dTodaysDate;
            careApp.PROCESSED_DATE__c = dTodaysDate;
            careApp.CC_CL_CD__c = listAcctDiscountType[0].Account_EI__r.CARE_DISCOUNT_TYPE__c;
            careApp.PER_ID__c = objOnDemandPEV.sPerId;
            careApp.CARE_Account_ID__c = objOnDemandPEV.sAccId;
            careApp.ACCT_ID__c = objOnDemandPEV.sBillingAccId;
            careApp.CCB_CONTACT_CODE__c = sCCContactCode;
            careApp.CCB_CONTACT_DESC__c= (sCCContactCode == listCareTypeVHE[0].TYPE_CODE__c) ? listCareTypeVHE[0].TYPE_DESC__c : listCareTypeVE[0].TYPE_DESC__c;
            careApp.CCB_CONTACT_COMMENT__c = (sCCContactCode == listCareTypeVHE[0].TYPE_CODE__c) ? listCareTypeVHE[0].TYPE_DESC_LONG__c : listCareTypeVE[0].TYPE_DESC_LONG__c;
            careApp.CCB_Contact_Type_No__c = (sCCContactCode == listCareTypeVHE[0].TYPE_CODE__c) ? listCareTypeVHE[0].TYPE_NO__c : listCareTypeVE[0].TYPE_NO__c;
        	careApp.ENROLLMENT_TYPE__c = 'OTHER'; //(sCCContactCode == listCareTypeVHE[0].TYPE_CODE__c) ? CARE_Constants.CARE_PEV_HU : CARE_Constants.CARE_PEV; //ENROLLMENT, PEV, PEV NOTICE, OTHER
            //careApp.ENROLLMENT_TYPE__c = 'PEV Receipt';
            //careApp.APPLICATION_EXTERNAL_ID__c = 'EN'; //EN or PE or BA
            careApp.APPLICATION_TYPE__c = CARE_Constants.CARE_PEV;     //Enrollment,PEV,Notice,Other  
            careApp.SOURCE_CHANNEL_TYPE__c = CARE_Constants.CARE_CHANNEL_TYPE_REGULAR_APP;
            careApp.HOUSE_QUALIFY__c = false; //Extra fields
            careApp.USER_NAME_CARE1__c = (userDetails.LAN_ID_EI__c != null) ? userDetails.LAN_ID_EI__c : '';//Extra fields  
            careApp.RESULT_DATE__c = dTodaysDate;//Extra fields
            
            listCareApp.add(careApp);
        
        Database.SaveResult[] srList = Database.insert(listCareApp, false);
        
        // Iterate through each returned result
        for (Database.SaveResult sr : srList) {
            if (sr.isSuccess()) {
                System.debug('Successfully inserted careApp--->: ' + sr.getId());
                OnDemandPEVWrapper.bSuccess = true;
                //careAppId = sr.getId();
                //System.debug('careAppId is--->: ' + careAppId);
            }
            else {
                // Operation failed, so get all errors               
                for(Database.Error err : sr.getErrors()) {
                    System.debug('The following error has occurred.');                   
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('CAre Application fields that affected this error: ' + err.getFields());
                }
            }
        } 
                      
          }catch (Exception ex) {
            EI_CreateErrorLog.upsertException(EI_CreateErrorLog.logException('CARE_OnDemandPEVController',ex));
            CARE_UtilityController.sendExceptionEmail('CARE_OnDemandPEVController','','',objOnDemandPEV.sPerId, ex);
        }
        
        
        return OnDemandPEVWrapper;
    }

}