force-app/main/default/objects/Account/fields/CARE_DISCOUNT_TYPE__c.field-meta.xml
<CustomField>
    <fullName>CARE_DISCOUNT_TYPE__c</fullName>
    <label>CARE DISCOUNT TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CARE</fullName>
            </value>
            <value>
                <fullName>FERA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CARE_ON_PROBATION__c.field-meta.xml
<CustomField>
    <fullName>CARE_ON_PROBATION__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CARE ON PROBATION</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>STANDARD</fullName>
            </value>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A10P</fullName>
            </value>
            <value>
                <fullName>A10PV</fullName>
            </value>
            <value>
                <fullName>A10PX</fullName>
            </value>
            <value>
                <fullName>A10S</fullName>
            </value>
            <value>
                <fullName>A10SV</fullName>
            </value>
            <value>
                <fullName>A10SX</fullName>
            </value>
            <value>
                <fullName>A10T</fullName>
            </value>
            <value>
                <fullName>A10TX</fullName>
            </value>
            <value>
                <fullName>A15</fullName>
            </value>
            <value>
                <fullName>A1F</fullName>
            </value>
            <value>
                <fullName>A1X</fullName>
            </value>
            <value>
                <fullName>A6</fullName>
            </value>
            <value>
                <fullName>ABS-TX3</fullName>
            </value>
            <value>
                <fullName>AG1A</fullName>
            </value>
            <value>
                <fullName>AG1B</fullName>
            </value>
            <value>
                <fullName>AG4A</fullName>
            </value>
            <value>
                <fullName>AG4B</fullName>
            </value>
            <value>
                <fullName>AG4C</fullName>
            </value>
            <value>
                <fullName>AG4D</fullName>
            </value>
            <value>
                <fullName>AG4E</fullName>
            </value>
            <value>
                <fullName>AG4F</fullName>
            </value>
            <value>
                <fullName>AG5A</fullName>
            </value>
            <value>
                <fullName>AG5B</fullName>
            </value>
            <value>
                <fullName>AG5C</fullName>
            </value>
            <value>
                <fullName>AG5D</fullName>
            </value>
            <value>
                <fullName>AG5E</fullName>
            </value>
            <value>
                <fullName>AG5F</fullName>
            </value>
            <value>
                <fullName>AGICE</fullName>
            </value>
            <value>
                <fullName>HAG1A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SA_Type__c.field-meta.xml
<CustomField>
    <fullName>SA_Type__c</fullName>
    <label>SA Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SAID__c.field-meta.xml
<CustomField>
    <fullName>SAID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SAID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Service_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Service Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Batch_Staging__c/CARE_Batch_Staging__c.object-meta.xml
<CustomObject>
    <label>CARE Batch Staging</label>
    <nameField>
        <displayFormat>CBS-{000000000}</displayFormat>
        <label>Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE Batch Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_Batch_Staging__c/fields/APPLICANT_NAME__c.field-meta.xml
<CustomField>
    <fullName>APPLICANT_NAME__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>APPLICANT NAME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Batch_Staging__c/fields/CARE_BILLING_ACCT_ID__c.field-meta.xml
<CustomField>
    <fullName>CARE_BILLING_ACCT_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>BILLING ACCT ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Batch_Staging__c/fields/EI_ACCOUNT__c.field-meta.xml
<CustomField>
    <fullName>EI_ACCOUNT__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EI ACCOUNT</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CARE Batch Staging</relationshipLabel>
    <relationshipName>CARE_Batch_Staging</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_Batch_Staging__c/fields/JOB_NO__c.field-meta.xml
<CustomField>
    <fullName>JOB_NO__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>JOB NO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Batch_Staging__c/fields/PER_ID__c.field-meta.xml
<CustomField>
    <fullName>PER_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PER ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Batch_Staging__c/fields/Processing_Message__c.field-meta.xml
<CustomField>
    <fullName>Processing_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Processing Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Batch_Staging__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <defaultValue>&quot;Loaded&quot;</defaultValue>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loaded</fullName>
                <default>true</default>
                <label>Loaded</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EI_Site__c/EI_Site__c.object-meta.xml
<CustomObject>
    <description>Sites are locations associated with Accounts, where work is performed.</description>
    <label>Site/Service Agreement</label>
    <nameField>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site/Service Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/EI_Site__c/fields/Account_EI__c.field-meta.xml
<CustomField>
    <fullName>Account_EI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site/Service Agreements (Account)</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EI_Site__c/fields/CARE_DISCOUNT_TYPE__c.field-meta.xml
<CustomField>
    <fullName>CARE_DISCOUNT_TYPE__c</fullName>
    <label>CARE DISCOUNT TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CARE</fullName>
            </value>
            <value>
                <fullName>FERA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EI_Site__c/fields/Care_Start_Date_EI__c.field-meta.xml
<CustomField>
    <fullName>Care_Start_Date_EI__c</fullName>
    <description>Care program start date.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Care program start date.</inlineHelpText>
    <label>Care Enroll Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EI_Site__c/fields/Care_Stop_Date_EI__c.field-meta.xml
<CustomField>
    <fullName>Care_Stop_Date_EI__c</fullName>
    <description>Care program Stop date.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Care program Stop date.</inlineHelpText>
    <label>Care Stop Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EI_Site__c/fields/Imported_Site_Name_EI__c.field-meta.xml
<CustomField>
    <fullName>Imported_Site_Name_EI__c</fullName>
    <description>The imported name of the Site/SA record</description>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Imported Site Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EI_Site__c/fields/Person_ID_EI__c.field-meta.xml
<CustomField>
    <fullName>Person_ID_EI__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Person ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EI_Site__c/fields/Rate_Schedule_EI__c.field-meta.xml
<CustomField>
    <fullName>Rate_Schedule_EI__c</fullName>
    <inlineHelpText>Please choose the Utility Rate schedule in effect for this Site location.</inlineHelpText>
    <label>Rate Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>STANDARD</fullName>
                <default>true</default>
                <label>STANDARD</label>
            </value>
            <value>
                <fullName>A1</fullName>
            </value>
            <value>
                <fullName>A10P</fullName>
            </value>
            <value>
                <fullName>A10PV</fullName>
            </value>
            <value>
                <fullName>A10PX</fullName>
            </value>
            <value>
                <fullName>A10S</fullName>
            </value>
            <value>
                <fullName>A10SV</fullName>
            </value>
            <value>
                <fullName>A10SX</fullName>
            </value>
            <value>
                <fullName>A10T</fullName>
            </value>
            <value>
                <fullName>A10TX</fullName>
            </value>
            <value>
                <fullName>A15</fullName>
            </value>
            <value>
                <fullName>A1F</fullName>
            </value>
            <value>
                <fullName>A1X</fullName>
            </value>
            <value>
                <fullName>A6</fullName>
            </value>
            <value>
                <fullName>ABS-TX3</fullName>
            </value>
            <value>
                <fullName>AG1A</fullName>
            </value>
            <value>
                <fullName>AG1B</fullName>
            </value>
            <value>
                <fullName>AG4A</fullName>
            </value>
            <value>
                <fullName>AG4B</fullName>
            </value>
            <value>
                <fullName>AG4C</fullName>
            </value>
            <value>
                <fullName>AG4D</fullName>
            </value>
            <value>
                <fullName>AG4E</fullName>
            </value>
            <value>
                <fullName>AG4F</fullName>
            </value>
            <value>
                <fullName>AG5A</fullName>
            </value>
            <value>
                <fullName>AG5B</fullName>
            </value>
            <value>
                <fullName>AG5C</fullName>
            </value>
            <value>
                <fullName>AG5D</fullName>
            </value>
            <value>
                <fullName>AG5E</fullName>
            </value>
            <value>
                <fullName>AG5F</fullName>
            </value>
            <value>
                <fullName>AGICE</fullName>
            </value>
            <value>
                <fullName>HAG1A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EI_Site__c/fields/Site_Premise_ID_EI__c.field-meta.xml
<CustomField>
    <fullName>Site_Premise_ID_EI__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Use for a utility-assigned Site / Premise ID, if applicable.</inlineHelpText>
    <label>Site/Premise ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EI_Site__c/fields/Svc_Status_Code_EI__c.field-meta.xml
<CustomField>
    <fullName>Svc_Status_Code_EI__c</fullName>
    <description>Status of this service agreement</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Status of this service agreement</inlineHelpText>
    <label>Service Status Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EI_Site__c/fields/Svc_Type_Code_EI__c.field-meta.xml
<CustomField>
    <fullName>Svc_Type_Code_EI__c</fullName>
    <description>E  (Electric) or G  (Gas)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>E  (Electric) or G  (Gas)</inlineHelpText>
    <label>Service Type Code</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CARE_ManualUploadTest.cls
/**************************************************************************************************   
Apex Batch Name      :  CARE_ManualUploadTest
Version              :  1.0                                                                          
Created Date         :  08/04/2020                                                              
Function             :  Test class for CARE_ManualUpload
Story                :                                                                               
Work Task            :                                                                            
Modification Log     :                                                                            
*--------------------------------------------------------------------------------------------------  
* Developer                 Date                   Description                                     
* -------------------------------------------------------------------------------------------------  
* A8AI                   08/20/2020               First Iteration  

***************************************************************************************************/
@isTest(SeeAllData = false)
public class CARE_ManualUploadTest {
    
    public static CARE_Batch_Staging__c careBatchStagingRecord1;
    public static CARE_Batch_Staging__c careBatchStagingRecord2;
    public static CARE_Batch_Staging__c careBatchStagingRecord3;
    public static CARE_Batch_Staging__c careBatchStagingRecord4;
    public static CARE_Batch_Staging__c careBatchStagingRecord5;
    
    public static EI_Bulk_Upload_History__c careBulkUploadHistory1;
    public static EI_Bulk_Upload_History__c careBulkUploadHistory2;
    
	public static List<Account> listAccountRecords = new List<Account>();
    public static List<EI_Site__c> listSiteRecords = new List<EI_Site__c>();
    public static List<CARE_Batch_Staging__c> careBatchStagingList = new List<CARE_Batch_Staging__c>();
    public static List<EI_Bulk_Upload_History__c> careBulkLoadList = new List<EI_Bulk_Upload_History__c>();
    
    @testSetup 
    public static void setup() {
        
        Account objAccountRecord = PM_EI_TestDataUtility.createAccount();
        objAccountRecord.AccountNumber = '1224590384';
        objAccountRecord.CARE_DISCOUNT_TYPE__c = 'CARE';
        objAccountRecord.Encrypted_Account_Name__c = 'Test Dummy Acct';
        objAccountRecord.SAID__c = '7777777777';
        objAccountRecord.Phone = '9065231';
        objAccountRecord.Discount__c = 'C';
        objAccountRecord.Billing_Person_ID_EI__c = '7437437437';
        objAccountRecord.Service_Address__c = 'Search1234';
        objAccountRecord.SA_Type__c = 'E';
        objAccountRecord.Encrypted_Account_Name__c = 'Encrypted';
        objAccountRecord.Type = 'Type';
        objAccountRecord.Rate__c = 'HAG1A';
        objAccountRecord.Branch_Code_EI__c = 'Get';
        objAccountRecord.Original_Tree_Level_EI__c = 2.0;
        objAccountRecord.CARE_ON_PROBATION__c = false;
        listAccountRecords.add(objAccountRecord);
        insert listAccountRecords;
        
         //Site record with status as '20', with valid Rate Schedule, and discount in 'Electric'
        EI_Site__c objSite1 = CARE_TestDataFactory.createSite(listAccountRecords);
        objSite1.Name='Site1';
        objSite1.Rate_Schedule_EI__c='STANDARD';
        objSite1.Imported_Site_Name_EI__c = 'MEDRANO,JOSE';
        objSite1.Site_Premise_ID_EI__c = '1212121212';
        objSite1.Care_Start_Date_EI__c = date.today();
        objSite1.Care_Stop_Date_EI__c = date.today()+30;
        objSite1.Svc_Status_Code_EI__c = '20';
        objSite1.Svc_Type_Code_EI__c = 'E';
        objSite1.Person_ID_EI__c = '7437437437';
        listSiteRecords.add(objSite1);
        
        EI_Site__c objSite2 = CARE_TestDataFactory.createSite(listAccountRecords);
        objSite2.Name='Site2';
        objSite2.Rate_Schedule_EI__c='STANDARD';
        objSite2.Imported_Site_Name_EI__c = 'MEDRANO,JOSE';
        objSite2.Site_Premise_ID_EI__c = '1212121212';
        objSite2.Care_Start_Date_EI__c = date.today();
        objSite2.Care_Stop_Date_EI__c = date.today()+30;
        objSite2.Svc_Status_Code_EI__c = '20';
        objSite2.Svc_Type_Code_EI__c = 'E';
        objSite2.Person_ID_EI__c = '1212121212';
        listSiteRecords.add(objSite2);
        insert listSiteRecords;
        
        //insert CARE BATCH STAGING Record
        careBatchStagingRecord1 = new CARE_Batch_Staging__c(PER_ID__c = '7437437437', APPLICANT_NAME__c = 'Test V Applicant1', EI_ACCOUNT__c = listAccountRecords[0].Id, 
                                                       CARE_BILLING_ACCT_ID__c = '9999999999', Processing_Status__c = 'Loaded', JOB_NO__c = 'CBJ-0016', Processing_Message__c = '');
        careBatchStagingRecord2 = new CARE_Batch_Staging__c(PER_ID__c = '3434343434', APPLICANT_NAME__c = 'Test V Applicant2', EI_ACCOUNT__c = listAccountRecords[0].Id, 
                                                       CARE_BILLING_ACCT_ID__c = '9999999999', Processing_Status__c = 'Loaded', JOB_NO__c = 'CBJ-0016', Processing_Message__c = '');
        careBatchStagingRecord3 = new CARE_Batch_Staging__c(PER_ID__c = '12121212ab', APPLICANT_NAME__c = 'Test VH Applicant1', EI_ACCOUNT__c = listAccountRecords[0].Id, 
                                                       CARE_BILLING_ACCT_ID__c = '9999999999', Processing_Status__c = 'Loaded', JOB_NO__c = 'CBJ-0016', Processing_Message__c = '');
        careBatchStagingRecord4 = new CARE_Batch_Staging__c(PER_ID__c = '7437437437', APPLICANT_NAME__c = 'Test V Applicant1', EI_ACCOUNT__c = listAccountRecords[0].Id, 
                                                       CARE_BILLING_ACCT_ID__c = '9999999999', Processing_Status__c = 'Loaded', JOB_NO__c = 'CBJ-0016', Processing_Message__c = '');
        careBatchStagingRecord5 = new CARE_Batch_Staging__c(PER_ID__c = '1919191919', APPLICANT_NAME__c = 'Test V Applicant1', EI_ACCOUNT__c = listAccountRecords[0].Id, 
                                                       CARE_BILLING_ACCT_ID__c = '9999999999', Processing_Status__c = 'Loaded', JOB_NO__c = 'CBJ-0017', Processing_Message__c = '');
        
        careBatchStagingList.add(careBatchStagingRecord1);
        careBatchStagingList.add(careBatchStagingRecord2);
        careBatchStagingList.add(careBatchStagingRecord3);
        careBatchStagingList.add(careBatchStagingRecord4);
        careBatchStagingList.add(careBatchStagingRecord5);
        insert careBatchStagingList;
        
        datetime NOW  = system.now();
        careBulkUploadHistory1 = new EI_Bulk_Upload_History__c(Account_EI__c = listAccountRecords[0].Id, File_Name_EI__c = 'V-CODEUPLOAD.csv', File_Upload_Date_EI__c = NOW,
                                                             Bulk_Upload_Sta_EI__c = 'Completed Successfully', File_Rec_Count_EI__c = 10, Error_Count_EI__c = 10,
                                                             Success_Count_EI__c = 0);
        careBulkUploadHistory2 = new EI_Bulk_Upload_History__c(Account_EI__c = listAccountRecords[0].Id, File_Name_EI__c = 'VH-CODEUPLOAD.csv', File_Upload_Date_EI__c = NOW,
                                                             Bulk_Upload_Sta_EI__c = 'Completed Successfully', File_Rec_Count_EI__c = 10, Error_Count_EI__c = 10,
                                                             Success_Count_EI__c = 0);
        
        careBulkLoadList.add(careBulkUploadHistory1);
        careBulkLoadList.add(careBulkUploadHistory2);
        insert careBulkLoadList;
    }
    
    @isTest
    public static void testManualUpload(){
       
        String sJobNo = 'CBJ-0016';
        Set<Id> cbsIdSet = new Set<Id>();
        List<CARE_Batch_Staging__c> cbsList = [SELECT Id, PER_ID__c FROM CARE_Batch_Staging__c WHERE PER_ID__c IN ('7437437437', '3434343434', '1919191919')];
        for(CARE_Batch_Staging__c cbs : cbsList){
        cbsIdSet.add(cbs.Id);    
        }
        String sLibName = 'Bulkload Home';
        String sResFileName = 'VCode_result_';
        List<EI_Bulk_Upload_History__c> bulkUploadList = [SELECT Id, File_Name_EI__c, Bulk_Upload_Sta_EI__c from EI_Bulk_Upload_History__c where File_Name_EI__c IN ('V-CODEUPLOAD.csv', 'VH-CODEUPLOAD.csv')];
        
        //String sArg = ('buhId'+':'+bulkUploadList[0].Id+','+'libraryName'+':'+sLibName);
        String jsonPass1 = '{"buhId":"' + String.valueOf(bulkUploadList[0].Id) + '", "libraryName":"' + sLibName + '"}';
        String jsonPass2 = '{"buhId":"' + String.valueOf(bulkUploadList[1].Id) + '", "libraryName":"' + sLibName + '"}';
        //String jsonData = JSON.serialize(sArg);
            
        Test.startTest();
        CARE_ManualUpload.getRecordsForManualLoad(sJobNo);
        CARE_ManualUpload.prepareResultCSV(cbsIdSet, bulkUploadList[0].Id, sLibName, sResFileName);
        CARE_ManualUpload.processVCode objManualVUpload = new CARE_ManualUpload.processVCode();
        objManualVUpload.execute(jsonPass1);
        CARE_ManualUpload.processVHCode objManualVHUpload = new CARE_ManualUpload.processVHCode();
        objManualVHUpload.execute(jsonPass2);
        Test.stopTest(); 
    }
    
}