force-app/main/default/objects/Account/fields/CARE_DISCOUNT_TYPE__c.field-meta.xml
<CustomField>
    <fullName>CARE_DISCOUNT_TYPE__c</fullName>
    <label>CARE DISCOUNT TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CARE</fullName>
            </value>
            <value>
                <fullName>FERA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/CARE_App_Enrolled_SA__c.object-meta.xml
<CustomObject>
    <description>SA(s) affected by the transaction in the CARE Application object</description>
    <label>CARE App Enrolled SA</label>
    <nameField>
        <displayFormat>CTSA{000000000}</displayFormat>
        <label>NAME  (APP SA Seq)</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE App Enrolled SA</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/ACCT_ID__c.field-meta.xml
<CustomField>
    <fullName>ACCT_ID__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>ACCT ID</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/APPLICATION__c.field-meta.xml
<CustomField>
    <fullName>APPLICATION__c</fullName>
    <label>APPLICATION</label>
    <referenceTo>CARE_Application__c</referenceTo>
    <relationshipLabel>CARE App Enrolled SA</relationshipLabel>
    <relationshipName>CARE_App_Enrolled_SA</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/CC_CL_CD__c.field-meta.xml
<CustomField>
    <fullName>CC_CL_CD__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CC CL CD</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/PER_ID__c.field-meta.xml
<CustomField>
    <fullName>PER_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PER ID</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/PREM_ID__c.field-meta.xml
<CustomField>
    <fullName>PREM_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PREM ID</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/RETRO_END_DATE__c.field-meta.xml
<CustomField>
    <fullName>RETRO_END_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RETRO END DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/RETRO_START_DATE__c.field-meta.xml
<CustomField>
    <fullName>RETRO_START_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RETRO START DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/RS_CD__c.field-meta.xml
<CustomField>
    <fullName>RS_CD__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RS CD</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/SA_ID__c.field-meta.xml
<CustomField>
    <fullName>SA_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SA ID</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_App_Enrolled_SA__c/fields/Service_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Service_Agreement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Agreement</label>
    <referenceTo>EI_Site__c</referenceTo>
    <relationshipLabel>CARE App Enrolled SA</relationshipLabel>
    <relationshipName>CARE_App_Enrolled_SA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/CARE_Application__c.object-meta.xml
<CustomObject>
    <label>CARE Application</label>
    <nameField>
        <displayFormat>CT-{0000000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CARE Application</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_Application__c/fields/ACCT_ID__c.field-meta.xml
<CustomField>
    <fullName>ACCT_ID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>ACCT ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/APPLICANT_NAME__c.field-meta.xml
<CustomField>
    <fullName>APPLICANT_NAME__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>APPLICANT NAME</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/APPLICATION_STATUS__c.field-meta.xml
<CustomField>
    <fullName>APPLICATION_STATUS__c</fullName>
    <inlineHelpText>Status of Enrollment</inlineHelpText>
    <label>APPLICATION STATUS</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Decision Made</fullName>
            </value>
            <value>
                <fullName>Staged for CC&amp;B</fullName>
            </value>
            <value>
                <fullName>Sent to CC&amp;B</fullName>
            </value>
            <value>
                <fullName>Reconciled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CARE_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>CARE_Account_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account number of customer enrolled</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CARE Application</relationshipLabel>
    <relationshipName>CARE_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CC_CL_CD__c.field-meta.xml
<CustomField>
    <fullName>CC_CL_CD__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>DISCOUNT TYPE</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/CCB_CONTACT_CODE__c.field-meta.xml
<CustomField>
    <fullName>CCB_CONTACT_CODE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CCB CONTACT CODE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/ENROLLMENT_TYPE__c.field-meta.xml
<CustomField>
    <fullName>ENROLLMENT_TYPE__c</fullName>
    <label>ENROLLMENT TYPE</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ENROLLMENT</fullName>
            </value>
            <value>
                <fullName>PEV</fullName>
            </value>
            <value>
                <fullName>PEV Receipt</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/PER_ID__c.field-meta.xml
<CustomField>
    <fullName>PER_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PER ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/PREM_ID__c.field-meta.xml
<CustomField>
    <fullName>PREM_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PREM ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/RETRO_END_DATE__c.field-meta.xml
<CustomField>
    <fullName>RETRO_END_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RETRO END DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/SOURCE_CHANNEL_TYPE__c.field-meta.xml
<CustomField>
    <fullName>SOURCE_CHANNEL_TYPE__c</fullName>
    <label>SOURCE CHANNEL TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Demand Status</fullName>
            </value>
            <value>
                <fullName>CARE Force.com</fullName>
            </value>
            <value>
                <fullName>CARE SMS</fullName>
            </value>
            <value>
                <fullName>CARE Flatsite</fullName>
            </value>
            <value>
                <fullName>CARE MyEnergy</fullName>
            </value>
            <value>
                <fullName>Regular App</fullName>
            </value>
            <value>
                <fullName>SoundBite</fullName>
            </value>
            <value>
                <fullName>Phone Enrollment</fullName>
            </value>
            <value>
                <fullName>Web Download</fullName>
            </value>
            <value>
                <fullName>Kiosk</fullName>
            </value>
            <value>
                <fullName>CASE/Adjustment</fullName>
            </value>
            <value>
                <fullName>CASE/Reinstatement</fullName>
            </value>
            <value>
                <fullName>CASE/Transfer</fullName>
            </value>
            <value>
                <fullName>CASE/Commodity</fullName>
            </value>
            <value>
                <fullName>PEV/Adjustment</fullName>
            </value>
            <value>
                <fullName>Enroll/Adjustment</fullName>
            </value>
            <value>
                <fullName>Bill Insert</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Allconnect</fullName>
            </value>
            <value>
                <fullName>ESA Enrollment</fullName>
            </value>
            <value>
                <fullName>DAC GT Enrollment</fullName>
            </value>
            <value>
                <fullName>Water Agency/IOU</fullName>
            </value>
            <value>
                <fullName>Batch</fullName>
            </value>
            <value>
                <fullName>DataXport Enrollment</fullName>
            </value>
            <value>
                <fullName>DataXport PEV Notice</fullName>
            </value>
            <value>
                <fullName>CARE New_Mover</fullName>
            </value>
            <value>
                <fullName>CARE IVR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CARE_Application__c/fields/START_DATE__c.field-meta.xml
<CustomField>
    <fullName>START_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>START DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_Type__c/CARE_Type__c.object-meta.xml
<CustomObject>
    <label>Reason/Contact Maintenance</label>
    <nameField>
        <displayFormat>CTNO-{000000}</displayFormat>
        <label>Seq No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reason/Contact Maintenance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CARE_Type__c/fields/END_DATE__c.field-meta.xml
<CustomField>
    <fullName>END_DATE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>END DATE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CARE_Type__c/fields/TYPE_CODE__c.field-meta.xml
<CustomField>
    <fullName>TYPE_CODE__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TYPE CODE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CARE_Type__c/fields/TYPE_DESC_LONG__c.field-meta.xml
<CustomField>
    <fullName>TYPE_DESC_LONG__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TYPE DESC LONG</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EI_Site__c/EI_Site__c.object-meta.xml
<CustomObject>
    <description>Sites are locations associated with Accounts, where work is performed.</description>
    <label>Site/Service Agreement</label>
    <nameField>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site/Service Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/EI_Site__c/fields/CARE_DISCOUNT_TYPE__c.field-meta.xml
<CustomField>
    <fullName>CARE_DISCOUNT_TYPE__c</fullName>
    <label>CARE DISCOUNT TYPE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CARE</fullName>
            </value>
            <value>
                <fullName>FERA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EI_Site__c/fields/Imported_Site_Name_EI__c.field-meta.xml
<CustomField>
    <fullName>Imported_Site_Name_EI__c</fullName>
    <description>The imported name of the Site/SA record</description>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>Imported Site Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EI_Site__c/fields/SA_Start_Date_EI__c.field-meta.xml
<CustomField>
    <fullName>SA_Start_Date_EI__c</fullName>
    <description>Service agreement start date</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Service agreement start date</inlineHelpText>
    <label>SA Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/EI_Site__c/fields/Svc_Type_Code_EI__c.field-meta.xml
<CustomField>
    <fullName>Svc_Type_Code_EI__c</fullName>
    <description>E  (Electric) or G  (Gas)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>E  (Electric) or G  (Gas)</inlineHelpText>
    <label>Service Type Code</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CARE_ReinstateController.cls
/***********************************************************************************************************   
Apex Util class Name :  CARE_ReinstateController
Version              :  1.0                                                                          
Created Date         :  05/27/2020                                                         
Function             :  This is the Apex Controller for Reinstate functionality for CARE Application Component.
Story                :                                                                               
Work Task            :                                                                               
Modification Log     :                                                                               
*----------------------------------------------------------------------------------------------------------  
* When                  Who                   								Description                                     
* ---------------------------------------------------------------------------------------------------------  
* 06/08/2020            Cognizant Technology Solutions                     Initial Version.
*                                                                          CARE Application: 
****************************************************************************************************************************************/

public with sharing class CARE_ReinstateController {
    
    //Constants 
     Private Static final Date dTodaysDate = Date.today();     
    
    //response Wrapper class for Reinstate Section
    public class WrapperReinstateResponse{
        @AuraEnabled
        public List<WrapperReinstate> listReinstate = new List<WrapperReinstate>();
        @AuraEnabled
        public List<WrapperReinstateReason> listReinstateReason = new List <WrapperReinstateReason>();
        @AuraEnabled
        public String sCommentWithAdjustment{get;set;}
        @AuraEnabled
        public String sCommentWithOutAdjustment{get;set;}
        @AuraEnabled 
        public Date dTodaysDate{get;set;}
        @AuraEnabled 
        public Date dDateBeforeNinetyDays{get;set;}
        @AuraEnabled
        public String sContactCode {get; set;}
        
        public WrapperReinstateResponse(){
            listReinstate = new List<WrapperReinstate>();
            listReinstateReason = new List<WrapperReinstateReason>();
            sCommentWithOutAdjustment = '';
            sCommentWithAdjustment = '';
            sContactCode = '';
        }
    }
    
    //response Wrapper class for Reinstate Section
    public class WrapperReinstate{
        @AuraEnabled
        public Id idSARecID {get; set;}
        @AuraEnabled
        public Id idAccountID {get; set;}
        @AuraEnabled
        public String sBillingAccountId {get; set;}
        @AuraEnabled
        public String sPremiseId {get; set;} 
        @AuraEnabled
        public String sSAId {get; set;}
        @AuraEnabled
        public String sSAType {get; set;}
        @AuraEnabled
        public String sDiscountType {get; set;}
        @AuraEnabled 
        public String sRateSchedule {get; set;}
        @AuraEnabled
        public Date dEndDate {get; set;}
        @AuraEnabled
        public Date dRetroStartDate {get; set;}
        @AuraEnabled
        public Date dRetroEndDate {get; set;}
        @AuraEnabled
        public Date dSAStartDate {get; set;}
        @AuraEnabled
        public String sApplicantName {get; set;}
    }
    
    public class WrapperReinstateReason{
        @AuraEnabled 
        public String label {get;set;}
        @AuraEnabled 
        public String value {get;set;}
    }
    
    //Input parameter from UI selected value
    public class ReinstateInputWrapper{
        @AuraEnabled 
        public String sPerId{get;set;}
        @AuraEnabled 
        public String sReason{get;set;}
        @AuraEnabled 
        public String sComment{get;set;}
        @AuraEnabled
        public String sContactCode{get;set;}
        
    }
    
    //Method to get the SA details for Reinstate modal pop up
    @AuraEnabled 
    public static WrapperReinstateResponse getReinstateDetails (String sPerId) {
        WrapperReinstateResponse reinstateResponse = new WrapperReinstateResponse();
        List<CARE_Type__c> listCareType = new List<CARE_Type__c>();
        String sLatestCareAppID;
        try{
            
            Map <String, EI_SITE__C> mapActiveSADiscountEnrollment = new Map <String ,EI_SITE__C >();
            mapActiveSADiscountEnrollment = CARE_UtilityController.getActiveSADetailsForPersonId(sPerId);   
            //check if customer is having an existing discount.
            if(!mapActiveSADiscountEnrollment.isEmpty()){
                
                return null;
            }
            else{                      
                //check if customer is having a previous active enrollent with Valid CC Code & Future End Date            
                List<CARE_App_Enrolled_SA__c> listCareAppEnrolledSA = new List <CARE_App_Enrolled_SA__c> ([SELECT SA_ID__c, START_DATE__c, END_DATE__c,Service_Agreement__r.Id, 
                                                                                                           Service_Agreement__r.Svc_Type_Code_EI__c, Service_Agreement__r.CARE_DISCOUNT_TYPE__c,
                                                                                                           Service_Agreement__r.SA_Start_Date_EI__c,
                                                                                                           Service_Agreement__r.Imported_Site_Name_EI__c,
                                                                                                           RS_CD__c, APPLICATION__c, ACCT_ID__c,
                                                                                                           PREM_ID__c, CC_CL_CD__c,
                                                                                                           RETRO_START_DATE__c, RETRO_END_DATE__c,APPLICATION__r.Id, 
                                                                                                           APPLICATION__r.CARE_Account_ID__c
                                                                                                           FROM CARE_App_Enrolled_SA__C 
                                                                                                           WHERE END_DATE__c>:dTodaysDate
                                                                                                           AND APPLICATION__r.PER_ID__C = : sPerID 
                                                                                                           AND  ((APPLICATION__r.CC_CL_CD__c =:CARE_Constants.CARE_CARE_DISCOUNT_TYPE AND APPLICATION__r.CCB_CONTACT_CODE__c IN: CARE_Constants.CARE_CC_CODE_CARE)
                                                                                                                 OR (APPLICATION__r.CC_CL_CD__c =:CARE_Constants.CARE_FERA_DISCOUNT_TYPE AND APPLICATION__r.CCB_CONTACT_CODE__c IN: CARE_Constants.CARE_CC_CODE_FERA)
                                                                                                                ) 
                                                                                                           ORDER BY APPLICATION__r.CreatedDate DESC]);
                //get the latest transaction record with a valid Rate Schedule & Status Code from history transaction
                if  (listCareAppEnrolledSA!= null && listCareAppEnrolledSA.size()>0 ){                    
                   sLatestCareAppID = listCareAppEnrolledSA[0].APPLICATION__c;
                    
                    for (CARE_App_Enrolled_SA__c careAppobj : listCareAppEnrolledSA){
                        
                        if(careAppobj.APPLICATION__c == sLatestCareAppID ){
                        
                        WrapperReinstate objRec = new WrapperReinstate ();
                        objRec.idSARecID = careAppobj.Service_Agreement__r.Id;
                        objRec.idAccountID = careAppobj.APPLICATION__r.CARE_Account_ID__c;
                        objRec.sBillingAccountId = careAppobj.ACCT_ID__C;
                        objRec.sPremiseId = careAppobj.PREM_ID__c;
                        objRec.sSAId = careAppobj.SA_ID__c;
                        objRec.sSAType = careAppobj.Service_Agreement__r.Svc_Type_Code_EI__c; 
                        objRec.sDiscountType = careAppobj.CC_CL_CD__c;
                        objRec.dEndDate = careAppobj.END_DATE__c;
                        objRec.sRateSchedule = careAppobj.RS_CD__c; 
                        objRec.dSAStartDate = careAppobj.Service_Agreement__r.SA_Start_Date_EI__c;
                        objRec.sApplicantName = careAppobj.Service_Agreement__r.Imported_Site_Name_EI__c;
                        
                        reinstateResponse.listReinstate.add(objRec);                        
                        }
                    }

                    //get the Transfer reason list  
                    List <String> listReinstateReason = CARE_UtilityController.getReasonList('Reinstatement Reason');
                    for(String sReasonRec : listReinstateReason){
                        
                        WrapperReinstateReason objReinstateReason = new WrapperReinstateReason ();
                        objReinstateReason.label = sReasonRec;
                        objReinstateReason.value = sReasonRec;  
                        reinstateResponse.listReinstateReason.add(objReinstateReason);
                    } 
                  
                    //get the cc code details for Reinstate reason without adjustment
                    listCareType = CARE_UtilityController.getCCCode(CARE_COnstants.CARE_CC_REINSTATE_NO_ADJUSTMENT,null,null);                
                    reinstateResponse.sCommentWithAdjustment = listCareType[0].TYPE_DESC_LONG__c;
                    
                    //get the cc code details for Reinstare reason with adjustment
                    listCareType = CARE_UtilityController.getCCCode(CARE_Constants.CARE_CC_REINSTATE_ADJUSTMENT,null,null);                
                    reinstateResponse.sCommentWithOutAdjustment = listCareType[0].TYPE_DESC_LONG__c;                    
                    reinstateResponse.dTodaysDate = dTodaysDate;
                    reinstateResponse.dDateBeforeNinetyDays = dTodaysDate.addDays(-90);
					reinstateResponse.sContactCode = listCareType[0].TYPE_CODE__c;
                        
                    return reinstateResponse;   
                }
                else{
                    return null;
                }                
            }
            
        }
        catch(Exception ex){
            system.debug(ex.getLineNumber()+ ': >' + ex.getMessage() + ': >' + ex.getStackTraceString());
        }
        return reinstateResponse ;
    }
    
    @AuraEnabled
    public static Boolean reinstateSA(String sPerId ,List<WrapperReinstate> listReinstateSA, ReinstateInputWrapper objReinstateInput, Boolean bIfAdjustment){
        Boolean bStatus;
        String sTypeNo;
        try{
            List<CARE_Type__c> listCareType = new List<CARE_Type__c>();
            List<CARE_App_Enrolled_SA__c>listCareAppEnrolledSA = new List<CARE_App_Enrolled_SA__c>();
            //get the cc code details for Reinstate based on Adjustment value.
            if(bIfAdjustment){
                sTypeNo = CARE_Constants.CARE_CC_REINSTATE_ADJUSTMENT;
                listCareType = CARE_UtilityController.getCCCode(sTypeNo,null,null);
            }
            else{
                sTypeNo = CARE_Constants.CARE_CC_REINSTATE_NO_ADJUSTMENT;
                listCareType = CARE_UtilityController.getCCCode(sTypeNo,null,null);
            }
            
            //get RecordType id from constant class
             Id careAppRecTypeId = CARE_UtilityController.getObjectRecordTypeId(CARE_Constants.RES_CUST_DEVELOPER_NAME);
            
            //create CARE APP Transaction To record the Resintate transaction         
            CARE_Application__c careAppObj = new CARE_Application__c();
            
            careAppobj.RecordTypeId = careAppRecTypeId;
            careAppobj.APPLICANT_NAME__c =  listReinstateSA[0].sApplicantName;
            careAppObj.APPLICATION_STATUS__c = 'Decision Made';
            careAppObj.ENROLLMENT_TYPE__c = 'OTHER';
            careAppobj.SOURCE_CHANNEL_TYPE__c = CARE_Constants.CARE_REINSTATE_SRC;
            careAppObj.PROCESSED_DATE__c  = dTodaysDate;
            careAppObj.PER_ID__c = sPerID;    
            careAppObj.CCB_CONTACT_CODE__c = listCareType[0].TYPE_CODE__c;
            careAppObj.CCB_CONTACT_DESC__c= listCareType[0].TYPE_DESC__c;
            careAppObj.CCB_CONTACT_COMMENT__c = objReinstateInput.sComment;//Comment updated in Modal 
            careAppObj.REASON_DESC__c = objReinstateInput.sReason; //Reason selected in Modal        
            careAppObj.CARE_Account_ID__c = listReinstateSA[0].idAccountID;//EI Account Id
            careAppObj.ACCT_ID__c = listReinstateSA[0].sBillingAccountId;
            careAppObj.CC_CL_CD__c = listReinstateSA[0].sDiscountType;            
            careAppobj.IS_ADJUSTMENT__c = bIfAdjustment;
            
            Insert careAppObj;            
            
            for ( WrapperReinstate reinstateSAObj :listReinstateSA ){
                CARE_App_Enrolled_SA__c careEnrolledSAObj = new CARE_App_Enrolled_SA__c(); 
                
                careEnrolledSAObj.ACCT_ID__c = reinstateSAObj.sBillingAccountId;
                careEnrolledSAObj.APPLICATION__c = careAppObj.Id;
                careEnrolledSAObj.Service_Agreement__c = reinstateSAObj.idSARecID;
                careEnrolledSAObj.CC_CL_CD__c = reinstateSAObj.sDiscountType;
                careEnrolledSAObj.CCB_CONTACT_TYPE__c = sTypeNo;
                careEnrolledSAObj.PER_ID__c = sPerID;
                careEnrolledSAObj.PREM_ID__c = reinstateSAObj.sPremiseId;
                careEnrolledSAObj.RS_CD__c = reinstateSAObj.sRateSchedule;
                careEnrolledSAObj.SA_ID__c = reinstateSAObj.sSAId;    
                careEnrolledSAObj.END_DATE__c = reinstateSAObj.dEndDate ;
                careEnrolledSAObj.SA_START_DATE__c = reinstateSAObj.dSAStartDate;
                
                //If adjustment is Selected record start Date & end Date
                if(bIfAdjustment){
                    careEnrolledSAObj.RETRO_START_DATE__c = reinstateSAObj.dRetroStartDate;
                    careEnrolledSAObj.RETRO_END_DATE__c = reinstateSAObj.dRetroEndDate;                    
                }
                //If Adjustment is not involved record last Billing cycle start date as Yes Date for each SA id ,time being stamp todaysDate
                else{
                    careEnrolledSAObj.START_DATE__C = dTodaysDate;
                }
                listCareAppEnrolledSA.add(careEnrolledSAObj);
                
            }           
            Insert listCareAppEnrolledSA;
            
            bStatus = true;
            
        }
        catch(Exception ex){
            system.debug(ex.getLineNumber()+ ': >' + ex.getMessage() + ': >' + ex.getStackTraceString());
        }
        return bStatus ;
    }
}